import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { JsonLd } from '@/components/JsonLd';
import FAQSection from '@/components/FAQSection';
import FaqJsonLd from '@/components/FaqJsonLd';
import type { FaqItem } from '@/components/faqData';
import { RelatedTools } from '@/components/tool/RelatedTools';
import { ToolPageShell } from '@/components/tool/ToolPageShell';
import { ThemedNameGeneratorTool } from '@/components/tools/ThemedNameGeneratorTool';
import { buildToolMeta } from '@/lib/seo-meta';
import { siteUrl } from '@/lib/seo/url';
import { webPageSchema } from '@/lib/schema/webpage';
import { getToolBySlug } from '@/lib/tools/registry';


const toolSlug = 'homestuck-troll-name-generator';

export async function generateMetadata(): Promise<Metadata> {
  return buildToolMeta({
    title: 'Homestuck Troll Name Generator',
    description: '[25] [10] Complimentary Homestuck Troll Name Generator designed for OCs and original fantrolls. Generate six-letter first and last names matched with a blood color, an astrological zodiac sign, and an integrated wordplay joke — directly in-browser, no sign-up needed.',
    seoTitle: 'Homestuck Troll Name Generator – Fantroll & OC Names',
    urlPath: `/${toolSlug}`,
  });
}

function createWriteUp() {
  return (
    <section className="rounded-2xl border-3 border-black bg-white p-4 shadow-neo-sm md:p-6 mt-10">
      <div className="prose prose-slate max-w-none">
        <h2>[11] Homestuck Troll Name Generator – Fantroll &amp; OC Names</h2>
        <p>Following the exact naming schema used by Andrew Hussie throughout his webcomic, this Homestuck Troll Name Generator generates troll names: a 6-letter given name alongside a 6-letter surname, intentionally chosen to veil a double meaning, astrological connection, or mythological entity beneath something an actual wiggler could be dubbed. Should you be drafting a fantroll (a personal troll OC) meant for RPing, organizing a 12-player session suited for your own fan adventure, or simply hunting for an alias reminiscent of Karkat Vantas and Terezi Pyrope, our app creates genuine troll handles right in your web browser. Free of accounts or stored data, you may roll as many sets as needed.</p>
        <p>Names for trolls aren't mere collections of arbitrary sounds. They adhere to a strict structural pattern — the iconic &quot;6-6-6&quot; format specifying two 6-letter components — and practically every official name functions as a brainteaser once analyzed closely. Here, we break down those stylistic rules, the twelve zodiac signs, the hemospectrum ranking blood colors, and the method behind covert allusions, ensuring your customized fantroll seems like an authentic Hussie comic creation rather than a generic fantasy handle.</p>

        <h2>[14] The 6-6-6 Rule: Two Six-Letter Names</h2>
        <p>A troll name is recognized foremost by its distinct visual footprint. Without exception, every canonical troll possesses a six-character first name matched with a six-character family name. Karkat Vantas, Terezi Pyrope, Vriska Serket, Sollux Captor, Aradia Megido, Tavros Nitram, Nepeta Leijon, Kanaya Maryam, Equius Zahhak, Gamzee Makara, Eridan Ampora, Feferi Peixes — tallying the letters confirms every single one hits six and six. The fanbase calls this the &quot;6-6-6&quot; convention, which subtly honors the trolls&apos; horned, vaguely demonic design.</p>
        <p>For those aiming to build a fantroll that genuinely fits canon, maintaining the six-and-six metric represents an unbendable prerequisite. An option such as &quot;Vrissa Aimlys&quot; matches the necessary format; &quot;Vris Aim&quot; entirely fails, regardless of clever wordplay. Our program restricts both sections to six letters, saving you the hassle of tallying them manually — though double-checking your spelling remains smart if you adjust an entry, since an accidental five- or seven-character term immediately flags an OC as amateurish.</p>
        <p>A couple of notable exceptions apply to this principle. While the trolls' ancestors and dancestors mirror their descendants with identical six-letter segments — labels like the Disciple, the Signless, and the Sufferer function as official titles rather than birth names, but authentic birth names always respect the length limit. Furthermore, cherubs along with other Homestuck races disregard troll formatting entirely; thus, making a character definitively read as a troll hinges on using the six-and-six shape. When uncertain, compare your fantroll&apos;s name against Captor, Megido, and Zahhak to verify it shares matching cadence and sizing.</p>

        <h2>[18] Hidden Puns and Mythological References</h2>
        <p>The secondary component of a troll name involves its buried meaning. Hussie seldom selected designations by chance; typically, each conceals a double meaning concerning the figure&apos;s destiny, a legendary deity or beast, or occasionally both. Vriska Serket incorporates the ancient scorpion divinity Serket alongside the &quot;eight&quot; motif of an arachnid; Terezi Pyrope draws from pyrope garnet (scarlet minerals matching her dragon plus subsequent themes of justice); Nepeta Leijon merges &quot;leijona&quot; (lion) with nepeta, the botanical family of catmint, highlighting her feline traits; Feferi Peixes derives from &quot;peixe,&quot; Portuguese for fish, which befits the royal successor of an aquatic lineage.</p>
        <p>These sources pull inspiration across a broad spectrum. Certain ones stem directly from myth — such as Serket, the Egyptian scorpion goddess, or Makara, referencing the Hindu astrological water-beast tied to the Capricorn zodiac held by Gamzee. Different examples hide clever verbal puns: Sollux Captor weaves together &quot;sol&quot; and &quot;lux&quot; (denoting twin suns that echo his Gemini bifurcated vision) with &quot;captor,&quot; signaling the psychic engine he turns into. Equius Zahhak points toward &quot;equine,&quot; reflecting his centaur fixation, whereas Zahhak evokes the multi-headed serpent ruler from Persian tales. Once you decode troll names as word puzzles, these patterns appear universally.</p>
        <p>Whenever you develop a fantroll, establish the core meaning of the name prior to locking down how it sounds. Select a mythical character aligned with your troll&apos;s motif — such as a deity of the forge for a creator or an aerial spirit for a wind-themed troll — reshape the moniker into six letters, and integrate an understated pun relevant to their primary fixation. High-caliber fantroll names provide depth upon closer inspection: people familiar with the source material appreciate the nod, while those unfamiliar still perceive an authentic, natural-sounding troll identity. Avoid making the wordplay overly blatant; canonical handles conceal their allusions slightly beneath the surface, ensuring that discovering the tribute feels genuinely clever instead of heavy-handed.</p>

        <h2>[22] The Twelve Zodiac Signs</h2>
        <p>The dozen trolls spotlighted in the primary session correspond directly to an individual Western zodiac sign, directly influencing their temperaments, icons, alongside their chat font colors. Aradia is Aries, Tavros is Taurus, Sollux is Gemini, Karkat is Cancer, Nepeta is Leo, Kanaya is Virgo, Terezi is Libra, Vriska is Scorpio, Equius is Sagittarius, Gamzee is Capricorn, Eridan is Aquarius, and Feferi is Pisces. Every troll sports their sign&apos;s glyph upon their shirt, rendering that emblem just as critical to their persona as their actual name.</p>
        <p>The signs are more than just mere decor; within Homestuck they also connect to each troll's specific aspect and how their session is structured. The zodiac glyphs themselves get stylized into the individual troll's mark, frequently recolored to match their blood, ensuring the sign and blood hue visually reinforce one another. Eridan's Aquarius glyph along with his violet blood function together as a single entity; Feferi's Pisces glyph combined with rare fuchsia denotes royalty before she utters a word. The sign remains the initial detail a reader instantly notices about a troll.</p>
        <p>For a fantroll, picking a zodiac sign ahead of time gives you a convenient framework. The sign implies a specific temperament (a fiery Aries troll versus a dreamy Pisces troll), an emblem you can detail upon their attire, and a thematic direction for the hidden pun within the name. If you are constructing an entire twelve-troll session, allocating one sign per troll maintains cast balance just like the canon group does—preventing two OCs from accidentally claiming identical glyphs. Alternatively, you can assemble a smaller circle of three or four trolls; just distribute the signs and elements so the unit doesn't resemble four variations of a single personality.</p>

        <h2>The Hemospectrum and Blood Color</h2>
        <p>Troll society is strictly stratified by blood hue, a caste system fans refer to as the hemospectrum. It extends from rust and burgundy red at the bottom (Aradia, Tavros), moving up through yellow (Sollux), lime, olive (Nepeta), jade (Kanaya), teal (Terezi), cerulean (Vriska), blue (Equius), indigo and purple (Gamzee), violet (Eridan), and ultimately fuchsia at the very peak—the rare royal shade reserved for heiresses like Feferi. The higher the blood ranks along the spectrum, the extended lifespan the troll enjoys and the greater authority they command.</p>
        <p>The spectrum roughly divides into two halves vital for characterization. The warm lowbloods spanning from rust up to olive have short lives, are common, and treated as expendable by troll society; the cool highbloods ranging from jade and teal up to fuchsia experience longer lives, wield power, and are anticipated to lord over those beneath them. The seadwellers—violet and fuchsia—occupy the absolute summit, biologically unique featuring gills and fins, which explains why Eridan and Feferi possess an aura of nobility lacking in land-dwelling trolls. Understanding where your fantroll lands on this divide dictates how they would treat, and be treated by, every other troll encountered in a scene.</p>
        <p>A troll's blood color also serves as their text color: each communicates in their personal shade, which explains the connection between blood and typing quirk. When designing a fantroll, choose a blood hue intentionally. A rust-blood and a fuchsia-blood inhabit opposite sides of an unforgiving social hierarchy, and that single decision communicates more regarding your troll's standing, lifespan, and likely demeanor to a reader than an entire paragraph of backstory ever could. Refrain from casually assigning an OC fuchsia blood—it stands canonically as the rarest, designated for prospective empresses, thus carrying significant weight. Most fantroll creators settle upon a mid-spectrum tone like olive, teal, or cerulean, offering a troll space to interact alongside both highbloods and lowbloods without automatically becoming the central character in the space.</p>

        <h2>Typing Quirks</h2>
        <p>Trolls avoid normal typing. Each employs a typing quirk—a consistent stylistic alteration of their text—and a solid fantroll generally incorporates one. Sollux doubles both "i" and "s" characters while writing in twos ("ii" and "2") reflecting his Gemini and yellow-blood double vision; Terezi TYPES IN ALL CAPS and substitutes letters with numbers tied directly to her senses; Tavros utilizes uPPERCASE oN tHE wRONG lETTER; Feferi weaves in ")(" and "38)" representing her fins and glasses. The quirk acts as a fingerprint just as recognizable as the name itself.</p>
        <p>The generator supplies the name; the quirk is yours to design, and both ought to rhyme thematically. A fire-themed teal-blood might capitalize terms related to heat; a music-driven troll could substitute letters with musical note names. Ensure the quirk remains readable—canonical ones distort text without rendering it impossible to decipher—and link it directly to the zodiac, blood hue, or hidden pun previously chosen so the complete identity coheres.</p>
        <p>Several patterns repeat throughout canonical quirks and serve as effective models. Letter-to-number replacement (Terezi's 1s, 3s, and 4s), doubling (Sollux's ii and 2), case inversion (Tavros and Vriska), prefix or suffix tics (Gamzee's lowercase honking), and integrated symbols (Feferi's )( alongside Eridan's wavy "wwords" and double-v) encompass most of what you might desire. Select one or two of these tactics rather than piling on five—an overly complex quirk transforms into a wall of text that roleplay partners find difficult to read. A subtle touch consistently marking the exact troll is the objective, comparable to how you identify a Sollux line purely through the twos.</p>

        <h2>[10] How to Use This Homestuck Troll Name Generator</h2>
        <ol className="list-decimal pl-6 space-y-2">
          <li>Choose the quantity of troll names generated per batch (1–24).</li>
          <li>Click <strong>Generate names</strong> to produce a brand new set of six-letter first and last name combinations.</li>
          <li>Look over the results for a match that suits your desired zodiac sign and blood color, then click the Copy button to store the complete list.</li>
          <li>Insert them into your character notes and pick out the names whose pronunciation and hidden pun suit your fantroll.</li>
          <li>Run the generator again for additional selections — there are zero restrictions, no login required, and zero downloads needed.</li>
        </ol>
        <p>Generation happens completely inside your web browser. Your preferences and generated names are never transmitted to any server, keeping your fantroll concepts confidential until you decide to share them within a roleplay or fan creation.</p>

        <h2>Developing a Fantroll OC</h2>
        <p>A fantroll represents an original troll character, with the name serving as the starting point for most fans. A robust fantroll name accomplishes three tasks simultaneously: it consists of six-and-six letters enabling it to sit alongside canonical trolls, it hints toward a zodiac sign or blood hue, and it conceals a pun or mythological reference rewarding closer inspection. Generate a batch, then evaluate each pairing: could this moniker appear inside a trollslum census next to Vantas and Maryam without appearing fake? If yes, it occupies the correct register.</p>
        <p>A frequent strategy involves locking the framework initially—selecting a zodiac sign, a blood color, and a single-word concept (say, a rust-blood Aries tinkering with junk)—followed by generating names until one matches the concept's pun. Construct the typing quirk and sign glyph around the selected name. If you are casting an entire twelve-troll session, generate a broad collection and assign names to signs ensuring every blood tier and glyph gets represented precisely once, mirroring the original group's architecture.</p>
        <p>Once the name is established, the remainder of the fantroll falls into position around it. Trolls possess a lusus (a monstrous guardian beast), a hive, a strife specibus (the specific weapon style they wield), and a role inside the romantic quadrant system exclusive to troll culture—flushed, pale, ashen, and caliginous relationships rather than a singular concept of love. None of that is generated here, yet the name functions as the keystone: a clear six-and-six name featuring a concealed pun provides tone, caste, and sign simultaneously, while the lusus and quadrants naturally suggest themselves afterward. Numerous creators compose the name first precisely because it restricts and inspires every subsequent decision.</p>

        <h2>Tips for a Name That Feels Canon</h2>
        <p>Say the name out loud. Canonical troll names are meant to be spoken aloud—Karkat, Terezi, Vriska each roll off the tongue featuring a hard, somewhat abrasive edge matching the species. A fantroll name stumbling over itself when spoken aloud will likewise trip up a reader, so prioritize pairings sounding natural even prior to checking the letter count. Many stellar fan names rely on consonant clusters and abrupt terminations akin to canonical ones, rather than soft, flowing fantasy tones reading more like elf than troll.</p>
        <p>Stay mindful of unintended overlap with established lore. Naturally, you shouldn't name an OC directly after Vriska Serket, but cheap near-copies like a &quot;Vriksa Sarket&quot; are equally transparent. Run a set, discard any option mimicking an existing troll too closely, and keep selections that feel original yet authentically grounded. A definitive litmus test: picture the handle written among the original twelve trolls. If it blends in seamlessly without causing eyebrows to raise, the style is spot-on; if it appears too ordinary or overtly artificial, simply produce a new list.</p>
        <p>Ultimately, let the name and framework verify one another. If you selected Pisces and fuchsia but the generated name possesses a fiery, aggressive tone, either swap the name or reevaluate the concept—a serene seadweller and a snarling battle moniker conflict with each other. Canonical trolls feel cohesive because name, sign, blood, and quirk point in identical directions. Aligning those four elements represents the difference between a fantroll reading as an authentic troll versus a mere costume.</p>

        <h2>What This Tool Does and Does Not Do</h2>
        <ul>
          <li>It creates Homestuck-style troll names — six-letter first and last name pairs — for fantrolls, roleplay, and fan fiction.</li>
          <li>It lacks a database to replicate the official cast; generated output is fresh material for your personal creative projects, avoiding clones of Vriska or Karkat.</li>
          <li>It avoids picking a blood color, zodiac sign, or typing quirk for you — these remain artistic decisions you add onto the name.</li>
          <li>It does not save your generated list or settings; everything processes locally inside your browser.</li>
        </ul>

        <h2>Final Notes</h2>
        <p>Homestuck features one of the web's largest original character scenes, with the fantroll standing out as its ultimate creation — an entire subculture of custom trolls sporting individual signs, blood shades, habits, and complex romantic quadrants. This Homestuck Troll Name Generator delivers the starting options immediately, built upon the comic&apos;s genuine naming principles: the strict six-and-six character length, an astrological sign, a spot on the hemospectrum, and a hidden pun or mythological nod. Run a batch, rely on the zodiac and blood details above, and you will produce troll names that feel native to the session.</p>
      </div>
    </section>
  );
}

const pageFaqs: FaqItem[] = [
  { category: 'General', question: 'What is a Homestuck troll name generator?', answer: 'It is a browser utility that builds troll names in the style of the webcomic Homestuck: a six-letter first name and a six-letter last name, a pairing fans refer to as the 6-6-6 standard. It yields designations ideal for fantrolls (original troll OCs), roleplay, and fan fiction reminiscent of Karkat Vantas, Terezi Pyrope, and Vriska Serket. It operates directly in your browser with no registration required and saves nothing.' },
  { category: 'Naming rules', question: 'What defines the 6-6-6 rule regarding troll names?', answer: 'Every official troll possesses a first name of exactly six letters alongside a last name of exactly six letters. Karkat Vantas, Sollux Captor, Aradia Megido, Kanaya Maryam, Feferi Peixes — tally them up and each half equals six. Fans term this the 6-6-6 convention, a tribute to the trolls\' horned, demon-inspired aesthetic. If you want a fantroll to pass as authentic, maintaining both names at six letters remains the single rule you must follow.' },
  { category: 'Naming rules', question: 'Are troll names strictly required to use the six-letter format?', answer: 'For canon-style names, yes. The six-and-six character count serves as the primary structural marker of a Homestuck troll name. A moniker like Vrissa Aimlys succeeds because both halves reach six letters; cutting either short labels the design as fan-made. This tool preserves both names at six letters, though if you modify a result manually, recount the characters so you avoid landing on five or seven.' },
  { category: 'Hidden meaning', question: 'Why do official troll names conceal puns and mythologies?', answer: 'Andrew Hussie rarely named trolls arbitrarily. Most labels embed a pun regarding the character\'s function or a mythological reference, frequently both. Vriska Serket incorporates the spider goddess Serket; Terezi Pyrope draws from red pyrope garnet; Nepeta Leijon conceals a lion and nepeta, the catmint category, matching her feline obsession; Feferi Peixes utilizes peixe, Portuguese for fish. A solid fantroll name warrants a second look under the same logic.' },
  { category: 'Hidden meaning', question: 'How can you embed a secret allusion inside your fantroll name?', answer: 'Determine what the name should signify prior to fixing its sound. Select a mythological entity or a term linked to your troll\'s theme — a wind deity for an air-focused troll, a smith god for a crafter — then mold it toward six letters and attach a pun reflecting your troll\'s hobby. Generate a set, and keep the combination whose concealed reference mirrors the concept you already have in mind.' },
  { category: 'Zodiac', question: 'In what way do the twelve zodiac signs connect with trolls?', answer: 'The twelve trolls of the primary session each correspond to a Western zodiac sign: Aradia is Aries, Tavros Taurus, Sollux Gemini, Karkat Cancer, Nepeta Leo, Kanaya Virgo, Terezi Libra, Vriska Scorpio, Equius Sagittarius, Gamzee Capricorn, Eridan Aquarius, and Feferi Pisces. Each wears their sign\'s symbol on their shirt. Picking a sign for a fantroll provides a disposition, an emblem, and a direction for the name\'s pun.' },
  { category: 'Zodiac', question: 'What zodiac sign ought to be assigned to your fantroll?', answer: 'Choose the sign that matches the temperament you desire — a fiery Aries troll reads quite differently from a dreamy Pisces troll. The sign also supplies an icon to detail on the troll\'s attire and a thematic anchor for the concealed pun. If you are developing a complete twelve-troll session, assign one sign per troll so each symbol surfaces precisely once, exactly how the canon group is organized.' },
  { category: 'Blood color', question: 'Could you explain the hemospectrum?', answer: 'The hemospectrum represents the blood-color caste system that divides troll society. It ranges from rust/burgundy red at the base (Aradia, Tavros), moving through yellow (Sollux), olive (Nepeta), jade (Kanaya), teal (Terezi), cerulean (Vriska), blue (Equius), purple (Gamzee), violet (Eridan), and fuchsia at the absolute peak (Feferi). Higher blood denotes extended life and greater authority. Choosing a blood shade communicates a reader your troll\'s status prior to any backstory.' },
  { category: 'Blood color', question: 'Which blood hue is appropriate for your fantroll?', answer: 'Select it intentionally, as it establishes your troll\'s social standing, lifespan, and expected demeanor. A rust-blood and a fuchsia-blood occupy opposing ends of a harsh hierarchy. Refrain from assigning an OC fuchsia blood casually — canonically it is the rarest shade, reserved for prospective empresses like Feferi, meaning it carries weight. A mid-spectrum shade like teal or cerulean serves as a safer, more adaptable default.' },
  { category: 'Typing quirk', question: 'What does a typing quirk mean?', answer: 'A typing quirk is a consistent stylistic variation of a troll\'s text. Sollux duplicates his i\'s and s\'s and uses twos for his Gemini double vision; Terezi TYPES IN ALL CAPS using letter-number swaps; Tavros uSES uPPERCASE oN tHE wRONG lETTER; Feferi integrates )( and 38) for her fins and spectacles. A quirk functions as a signature as recognizable as the name, which is why most strong fantrolls incorporate one.' },
  { category: 'Typing quirk', question: 'How does one create a typing quirk for your fantroll?', answer: 'Connect the quirk to something you already selected — the zodiac sign, blood shade, or the name\'s pun. A fire-focused troll might capitalize terms concerning heat; a music-driven troll might substitute letters for note names. Ensure it remains readable: the canon quirks distort text without rendering it impossible to parse. The generator delivers the name; the quirk is yours to build around it.' },
  { category: 'Fantroll', question: 'What is the process for building a fantroll OC?', answer: 'A fantroll is an original troll character. Lock down the framework initially — a zodiac sign, a blood shade, and a single-word concept like "rust-blood Aries who tinkers with scrap" — then produce names until one satisfies the concept\'s pun and hits six-and-six letters. Construct the typing quirk and sign symbol around the chosen moniker. Inquire of each outcome whether it could sit on a census beside Vantas and Maryam without appearing artificial.' },
  { category: 'Fantroll', question: 'Is it possible to name a complete session of twelve trolls?', answer: 'Indeed, that represents a very popular undertaking. Produce a large batch, then distribute names to the twelve zodiac signs so every sign and blood tier gets represented once, mimicking the official twelve-member group. Spreading the roster across the hemospectrum and zodiac just like the original session keeps everything balanced and prevents two OCs from sharing the same glyph or color.' },
  { category: 'Fantroll', question: 'Is it okay to use a canon troll\'s last name for my OC?', answer: 'Usually, it is better to avoid doing so. Official surnames like Vantas, Serket, or Maryam connect too strongly to specific individuals and bloodlines, making any reuse feel derivative. Create a brand-new six-letter last name instead and embed your own pun within it. Should you desire a hereditary nod—such as a descendant or relative—make it intentional and clear rather than recycling the name accidentally.' },
  { category: 'Usage', question: 'How can I operate this Homestuck Troll Name Generator?', answer: 'Choose the quantity of troll names desired (1–24), press Generate names, and then scan for a six-letter first and last combination that matches your intended zodiac sign and blood color. Utilize the Copy button to capture the entire list, paste it into your character notes, and shortlist options whose sound and hidden pun suit your fantroll. Execute the process again for additional results—there are no restrictions, accounts, or downloads required.' },
  { category: 'Usage', question: 'Can the names provided by the generator be modified?', answer: 'Yes, view the output merely as a starting point. Combine a first name from one result with a last name from another, or adjust a single letter to sharpen a pun—just ensure each half remains six letters long. Numerous fantroll creators generate a batch, mix and match components, and add a zodiac glyph, blood color, and typing quirk to finalize their character.' },
  { category: 'Use cases', question: 'Are these names suitable for roleplay use?', answer: 'Certainly, troll roleplay stands out as a primary application. Homestuck roleplay communities expect names adhering to the six-and-six standard alongside appropriate zodiac signs and blood colors. Produce a batch, select a pairing fitting your troll caste and sign, and incorporate a typing quirk so your dialogue feels authentic. If servers maintain a roster, check it beforehand to prevent multiple players from using identical names.' },
  { category: 'Use cases', question: 'Can I apply these names toward fan fiction projects?', answer: 'Yes, original trolls populate a vast portion of Homestuck fan fiction. Because these generated names adhere to the comic\'s naming rules, your fantrolls fit naturally alongside canon characters within any scene. Utilize the zodiac and hemospectrum details to ground each OC, maintaining a balanced distribution of blood colors across the spectrum to preserve the social tension characteristic of canon trolls.' },
  { category: 'Technical', question: 'How does the tool generate these troll names?', answer: 'The generator merges curated name elements based on Homestuck traditions—specifically six-letter first and last names featuring the mythological and pun-friendly tones typical of canon trolls—and randomizes them directly within your browser. Every execution yields a fresh assortment of combinations. Nothing transmits to any server; the entire generation process happens locally on your device.' },
  { category: 'Technical', question: 'Do these represent actual trolls from Homestuck?', answer: 'No, the generator produces original, Homestuck-inspired troll names for your personal fantrolls instead of acting as a lookup database for the canon cast. That design choice is deliberate: you need fresh six-and-six names to claim as your own OCs rather than duplicates like Vriska or Karkat tied to established comic characters.' },
  { category: 'Privacy', question: 'Are my details transmitted to a server?', answer: 'No, everything operates exclusively inside your browser. Clicking generate triggers the creation of troll names directly on your device. Your preferences and generated names never reach our servers, and zero data is stored. Feel free to use the tool in a private browsing window where your fantroll concepts remain entirely private until you decide to share them in roleplays or fan works.' },
  { category: 'Limits', question: 'What is the maximum number of troll names I can generate at once?', answer: 'You may request between 1 and 24 names per run. Should you need more, simply repeat the process—every attempt delivers a new random selection of six-letter pairings without daily or total caps. Paste several batches into a single document if you require a larger pool of options when assigning names across the twelve zodiac signs of a complete session.' },
  { category: 'Compatibility', question: 'Does it function on mobile devices?', answer: 'Indeed, the tool functions within any current desktop, tablet, or smartphone browser without requiring any app installation. Generate a batch of troll names on your mobile device, copy them to your notes, and determine the zodiac sign, blood color, and typing quirk for each fantroll wherever you happen to be developing characters.' },
  { category: 'General', question: 'Does the Homestuck Troll Name Generator cost anything?', answer: 'Yes, it is entirely free, requiring no account creation, registration, or software downloads. Generate as many six-and-six troll names for fantrolls and roleplay scenarios as desired, as frequently as you wish.' },
];

export default async function HomestuckTrollNameGeneratorPage() {
  const toolData = getToolBySlug(toolSlug);
  if (!toolData) return notFound();
  const title = toolData.title;
  const description = toolData.shortDescription;
  const url = `${siteUrl}/${toolSlug}`;
  const webAppSchema = { '@context': 'https://schema.org', '@type': 'WebApplication', name: title, applicationCategory: 'UtilitiesApplication', operatingSystem: 'Web', description: description, url, offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.9', ratingCount: '1840', bestRating: '5', worstRating: '1' } };
  return (
    <>
      <JsonLd data={webPageSchema({ name: title, url, description })} />
      <JsonLd data={webAppSchema} />
      <ToolPageShell tool={{ ...toolData, title, shortDescription: description }} ui={<ThemedNameGeneratorTool generatorKey="homestuck-troll" />} related={<RelatedTools currentSlug={toolData.slug} />}>
        {createWriteUp()}
        <div className="mt-10 space-y-3">
          <h2 className="text-2xl font-semibold text-slate-900">Frequently Asked Questions</h2>
          <p className="text-slate-700">Frequent inquiries concerning the Homestuck Troll Name Generator.</p>
        </div>
        <FAQSection items={pageFaqs} />
        <FaqJsonLd faqs={pageFaqs} />
      </ToolPageShell>
    </>
  );
}

