import React from 'react';
import type { ToolContent } from '@/lib/tools/content/types';

const WriteUp = () => (
  <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:p-6 mt-10"><div className="prose prose-slate max-w-none">
    <h2 className="text-2xl font-bold text-slate-900 mb-4">Arabic AI Detector: Identify AI-Generated Text in Modern Standard Arabic and Dialects</h2>
    <p className="text-slate-700 mb-4">Arabic presents the most complex AI detection challenge of any widely spoken language due to a fundamental structural feature: diglossia. Arabic speakers navigate between two substantially different linguistic systems — Modern Standard Arabic (MSA, or Fusha), the formal written language used for education, official communication, journalism, and literature across the Arab world; and their regional colloquial dialect (ammiya), the spoken variety used for everyday communication that varies dramatically across Egypt, the Levant, the Gulf, the Maghreb, and other regions. AI systems writing in Arabic must navigate this diglossia, and their handling of it — where they default to MSA when colloquial would be more natural, where they mix the two inappropriately, and where their MSA lacks the specific rhetorical authenticity of educated Arab writers — creates detectable signatures that the Arabic AI Detector identifies.</p>
    <p className="text-slate-700 mb-4">The Arabic detection challenge is compounded by the fact that authentic Arabic writing itself spans a wide spectrum. Classical Arabic (Classical Quranic Arabic) represents the highest register; Modern Standard Arabic is the contemporary formal standard; then there are intermediate registers mixing MSA and colloquial elements; then fully colloquial writing in Egyptian Arabic, Levantine Arabic, Gulf Arabic, Maghrebi Arabic, and other varieties. AI systems have been trained on MSA-dominant data with limited authentic colloquial representation, creating AI Arabic that is disproportionately MSA-formal even in contexts where authentic Arab writers would use colloquial or mixed registers. This formality mismatch is the most reliable cross-context Arabic AI detection signal.</p>
    <p className="text-slate-700 mb-4">The institutional demand for Arabic AI detection spans the entire Arab world and the global Arabic-speaking diaspora. Arab universities from Morocco to Kuwait collectively serve millions of students writing in Arabic. Arabic media organizations — Al Jazeera, Al Arabiya, major print newspapers — face AI-generated content challenges. Arabic corporate communications, government information, religious content, and the growing Arabic digital content economy all represent contexts where authenticity of authorship matters. The right-to-left script, the complex morphological system, and the diglossia challenge all require Arabic-specific detection capability that generic multilingual tools cannot provide.</p>

    <h3 className="text-xl font-semibold text-slate-800 mb-3">Arabic Diglossia and AI Detection</h3>
    <p className="text-slate-700 mb-4">Diglossia creates the central detection axis for Arabic AI content. Authentic Arabic writers deploy MSA and colloquial Arabic with contextual intelligence developed through years of navigating the Arabic linguistic landscape. A well-educated Egyptian journalist writing formally for a newspaper produces clean MSA with specific Egyptian rhetorical influences; the same journalist writing a WhatsApp message produces colloquial Egyptian Arabic; writing a popular article for a digital platform, they may produce a carefully calibrated MSA-ammiya blend that feels accessible without being informal. AI systems lack this contextual calibration — they predominantly produce MSA regardless of context because MSA dominates their training data, creating register inappropriateness that native Arabic speakers detect immediately even if they articulate it as "this writing feels stiff."</p>
    <p className="text-slate-700 mb-4">Register analysis is therefore the primary detection tool for Arabic. When the context calls for colloquial Arabic — social media, personal blogs, informal journalism, marketing targeting everyday Arabic audiences — and the text is written in pure MSA without any colloquial markers, this mismatch between expected register and actual register strongly indicates AI generation. The detector&#39;s register context assessment identifies what register each content context calls for and evaluates whether the actual text register matches context-appropriate expectations. MSA that is appropriate for a formal newspaper editorial passes without flagging; MSA that appears in a context calling for colloquial registers triggers detection alerts.</p>
    <p className="text-slate-700 mb-4">Within MSA, AI-generated Arabic exhibits specific signatures beyond register mismatch. AI Arabic shows characteristic overuse of formal MSA transitional phrases — min hadha al-manthiq (from this logic), tajduru al-ishara ila anna (it is worth noting that), wa ala hadha al-asas (and on this basis) — that appear with formulaic regularity in AI-generated MSA regardless of whether they are rhetorically appropriate. Authentic MSA writers use these connectors selectively, often preferring simpler parataxis or less formulaic transitions. The frequency and placement analysis of these formal connectors is a reliable AI signal within formal MSA writing.',</p>

    <h3 className="text-xl font-semibold text-slate-800 mb-3">Arabic Regional Variety Detection</h3>
    <p className="text-slate-700 mb-4">When AI systems attempt to produce regional colloquial Arabic, they typically produce what Arabic linguists call "pseudo-dialect" — text that includes some regional vocabulary items but lacks the authentic grammatical structures, idiomatic expressions, and pragmatic conventions of the actual regional variety. Egyptian Arabic AI detection is well-developed because Egyptian Arabic is the most widely represented Arabic colloquial variety in AI training data. Even with this relative advantage, AI-generated Egyptian Arabic shows characteristic shortcomings: grammatical structures that don&#39;t match authentic Egyptian dialectal grammar, idiomatic expressions that are half-recalled from MSA context rather than authentic Egyptian expressions, and the absence of Egyptian-specific pragmatic conventions around politeness, humor, and directness.',</p>
    <p className="text-slate-700 mb-4">Levantine Arabic (Syrian, Lebanese, Palestinian, Jordanian) AI generation shows even clearer inauthenticity because of relatively lower training data representation. Levantine Arabic has specific phonologically-influenced orthographic conventions — certain sounds represented distinctively in Levantine writing — and specific grammatical structures that AI systems approximate imperfectly. Gulf Arabic AI generation similarly produces pseudo-dialect rather than authentic Gulf Arabic, with specific Khaleeji vocabulary items inserted into largely MSA grammatical structures that don&#39;t reflect authentic Gulf Arabic grammar. The detector&#39;s regional variety analysis identifies these pseudo-dialect characteristics as AI signals.',</p>
    <p className="text-slate-700 mb-4">Maghrebi Arabic detection presents particular challenges because Maghrebi colloquial Arabic (Darija in Morocco and Algeria, Tunisian Arabic) has been significantly influenced by French and Berber languages, creating distinctively different Arabic varieties from Middle Eastern colloquials. AI systems are particularly poor at generating authentic Maghrebi Arabic, tending to produce either MSA or pseudo-Egyptian Arabic rather than authentic Darija or Tunisian Arabic. When content claims to be Maghrebi Arabic, the almost certain inability of current AI systems to produce authentic Maghrebi colloquial means that authentic-looking Maghrebi content is most likely human-written while AI-generated content will show clear MSA or Egyptian influence.',</p>

    <h3 className="text-xl font-semibold text-slate-800 mb-3">Arabic Academic Writing Detection</h3>
    <p className="text-slate-700 mb-4">Arabic academic writing has been shaped by diverse influences: the classical Arabic literary tradition, the European-influenced formal academic style adopted during the nahda (Arab renaissance) period, and more recently the internationalization of Arabic academic writing influenced by Anglophone scientific publishing norms. Arabic universities from Egypt and Saudi Arabia to Morocco and Iraq have different academic writing traditions reflecting their specific educational histories. Detection for Arabic academic writing requires calibration against this diversity of authentic Arabic academic conventions rather than applying a single Arabic academic writing norm.',</p>
    <p className="text-slate-700 mb-4">The Arabic research article in social sciences, humanities, and Islamic studies has specific rhetorical conventions — specific ways of positioning research within Islamic scholarly tradition, specific citation practices for classical Arabic sources alongside contemporary literature, specific argumentation patterns shaped by Arabic logical and rhetorical traditions. AI-generated Arabic academic writing in these fields often produces formally correct MSA that lacks the specific rhetorical authentication that engagement with Arabic intellectual tradition produces. These rhetorical authenticity signals are detectable through pattern analysis calibrated against authentic Arabic academic writing in each discipline.',</p>
    <p className="text-slate-700 mb-4">Arabic STEM academic writing faces the same internationalization challenge that Russian STEM writing faces — legitimate contemporary Arabic STEM writing blends Arabic with English technical terminology and international scientific writing conventions in ways that generic Arabic detectors might flag incorrectly. The detector&#39;s Arabic STEM calibration recognizes this legitimate hybrid style and focuses detection on the MSA-only signals and rhetorical authenticity signals that distinguish AI Arabic from authentic contemporary Arabic STEM writing.',</p>

    <h3 className="text-xl font-semibold text-slate-800 mb-3">Arabic Morphology and Script Processing</h3>
    <p className="text-slate-700 mb-4">Arabic&#39;s root-and-pattern morphology is one of the most complex morphological systems of any widely spoken language. Arabic words are derived from three or four-letter root consonants combined with vowel patterns (wazn) to produce words with related meanings. This system creates a vocabulary generation mechanism that AI systems handle with varying authenticity — sometimes producing morphologically correct but unusual or unnatural word forms, sometimes choosing the grammatically valid but stylistically inappropriate form from multiple morphologically equivalent options. Morphological naturalness analysis is a sophisticated Arabic AI detection signal that requires Arabic-specific morphological processing.',</p>
    <p className="text-slate-700 mb-4">Arabic script processing requires specific technical capabilities. Arabic is written right-to-left with letters that change form depending on their position in a word (initial, medial, final, isolated forms). Arabic text lacks vowel diacritics (harakat) in most written contexts except the Quran and children&#39;s educational materials — readers must infer vowels from context. The detector processes Arabic text with correct handling of Arabic Unicode encoding, right-to-left text directionality, connected script forms, and optional diacritics. Preprocessing handles common encoding issues in Arabic digital text and correctly processes the full range of Arabic characters including hamza forms and the different forms of alef.',</p>
    <p className="text-slate-700 mb-4">The Arabic AI Detector achieves approximately 83% true positive rate and 85% true negative rate on benchmark test sets covering both MSA and major colloquial variety AI detection. Arabic detection presents the highest challenges of any detection language due to diglossic complexity and the diversity of authentic Arabic writing conventions. MSA detection is somewhat more reliable (87%+) than colloquial dialect detection (78-82%) where AI and human writing converge more and where colloquial variety-specific training data is more limited. Benchmarks are updated quarterly.',</p>

    <h3 className="text-xl font-semibold text-slate-800 mb-3">Islamic and Religious Content Detection</h3>
    <p className="text-slate-700 mb-4">Religious Arabic content — Quranic commentary (tafsir), Islamic legal opinion (fatwa), religious educational content — represents a distinctive genre with its own detection challenges. Classical Quranic Arabic and the language of the Hadith and classical Islamic scholarship form the highest register of the Arabic literary-linguistic tradition, and authentic Islamic scholarly writing makes specific and contextually appropriate use of classical Arabic sources. AI-generated Islamic content often reproduces surface Islamic vocabulary and formulaic phrases without the authentic deep engagement with Islamic scholarly tradition that characterizes authentic religious Arabic writing. Detection for religious Arabic content requires specific calibration for the classical register and genre conventions of Islamic scholarly writing.',</p>
    <p className="text-slate-700 mb-4">The proliferation of AI-generated Islamic content — religious rulings, educational materials, devotional content — raises specific authenticity concerns beyond normal AI detection contexts. Religious audiences have expectations of scholarly authenticity in religious content that go beyond general authenticity expectations. Detection capability for religious Arabic content supports institutions and scholars in verifying that content attributed to specific scholars or religious authorities represents authentic scholarship rather than AI-generated content. This is a sensitive application area where the tool provides technical capability while leaving judgment about religious authenticity to qualified Islamic scholars.',</p>
  </div>
</section>
);

export const arabicAiDetectorContent: ToolContent = {
  writeUp: <WriteUp />,
  faqs: [
    {
      category: 'general',
      question: 'What is diglossia and why does it make Arabic AI detection uniquely challenging?',
      answer: 'Arabic diglossia refers to the coexistence of two substantially different linguistic systems: Modern Standard Arabic (MSA/Fusha), used for formal written communication across the Arab world, and regional colloquial dialects (ammiya), used for everyday spoken communication. These varieties differ in vocabulary, grammar, and pragmatic conventions. AI systems predominantly generate MSA regardless of context because MSA dominates their training data, creating a systematic register mismatch when colloquial Arabic would be more appropriate. This MSA default — formal Arabic in contexts calling for colloquial — is the most reliable cross-context Arabic AI detection signal, detectable through register context analysis.',
    },
    {
      category: 'detection',
      question: 'What are the most reliable Arabic AI writing signatures?',
      answer: 'Key Arabic AI signals include: register inappropriateness — MSA in contexts calling for colloquial or mixed register; formal connector overuse — min hadha al-manthiq, tajduru al-ishara ila, wa ala hadha al-asas appearing at formulaic intervals; pseudo-dialect production — colloquial vocabulary items inserted into essentially MSA grammatical structures rather than authentic dialectal grammar; morphological unnaturality — technically valid but stylistically unusual word forms from Arabic\'s root-and-pattern morphology; and rhetorical inauthenticity — correct MSA without the specific rhetorical engagement with Arabic intellectual tradition that authentic Arab scholars produce.',
    },
    {
      category: 'regional',
      question: 'How does the detector handle Egyptian, Levantine, Gulf, and Maghrebi Arabic?',
      answer: 'Regional variety detection identifies "pseudo-dialect" — AI text with some regional vocabulary but lacking authentic regional grammatical structures, idioms, and pragmatic conventions. Egyptian Arabic detection is most reliable because Egyptian Arabic is most-represented in AI training data. Levantine Arabic (Syrian, Lebanese, Palestinian, Jordanian) and Gulf Arabic (Khaleeji) detection identifies MSA grammatical structures with regional vocabulary inserts as pseudo-dialect. Maghrebi Arabic (Moroccan/Algerian Darija, Tunisian Arabic) is the clearest case — AI systems almost cannot produce authentic Maghrebi colloquial, so content claiming to be authentic Darija that avoids this regional variety limitation is likely AI-generated.',
    },
    {
      category: 'academic',
      question: 'How does Arabic academic writing detection work across Arab universities?',
      answer: 'Arabic academic writing varies across the Arab world — Egyptian, Saudi, Moroccan, and Iraqi universities have different academic writing traditions shaped by their educational histories and linguistic influences. The detector calibrates against this diversity rather than applying a single Arabic academic norm. Arabic STEM writing legitimately blends Arabic with English technical terminology and international scientific conventions; this hybrid is recognized as authentic contemporary Arabic STEM writing rather than flagged. Arabic humanities and social science writing retains more traditional MSA rhetorical conventions; detection in these contexts focuses on rhetorical authenticity signals absent in AI-generated Arabic scholarly text.',
    },
    {
      category: 'detection',
      question: 'How does Arabic morphology analysis contribute to detection?',
      answer: 'Arabic\'s root-and-pattern morphology creates a system where words are derived from three or four-letter root consonants combined with vowel patterns. This creates multiple morphologically valid forms for many meanings, and AI systems sometimes choose technically correct but stylistically unusual or unnatural forms. Morphological naturalness analysis assesses whether the specific word forms used in the text represent the forms that native Arabic writers would naturally choose, or whether they represent less natural alternatives that AI systems produce due to incomplete internalization of authentic Arabic morphological preferences. This analysis requires Arabic-specific morphological processing unavailable in generic multilingual tools.',
    },
    {
      category: 'technical',
      question: 'How does the detector handle Arabic script and encoding?',
      answer: 'Arabic script processing handles Unicode Arabic text with correct right-to-left directionality, letter contextual forms (initial, medial, final, isolated), hamza forms (أ إ آ ء ؤ ئ), and the special alef forms. Optional diacritic handling correctly processes texts with and without harakat (vowel marks). Preprocessing normalizes common Arabic encoding variations and OCR errors in scanned Arabic documents (alef-hamza confusion, yaa/alef maqsoura confusion are common). Arabic digits versus Western numerals are handled correctly. The tool processes classical Arabic encoding alongside contemporary Arabic, important for texts that quote Quranic or classical Arabic sources.',
    },
    {
      category: 'accuracy',
      question: 'What is the detection accuracy for Arabic AI content?',
      answer: 'The detector achieves approximately 83% true positive rate and 85% true negative rate on benchmark test sets covering both MSA and major colloquial variety detection. Arabic presents the highest detection challenges due to diglossic complexity and authentic writing diversity. MSA detection is more reliable (87%+) than colloquial dialect detection (78-82%). Register-mismatch detection (MSA in colloquial-context) has the highest accuracy (90%+). Benchmarks are updated quarterly against current AI model Arabic outputs. All probability scores include confidence bounds for informed decision-making. High-confidence Arabic detections warrant investigation; ambiguous scores should receive additional human review given inherent detection uncertainty.',
    },
    {
      category: 'academic',
      question: 'Can Arab universities use the detector for academic integrity?',
      answer: 'Yes, Arabic academic integrity is a primary application. Calibration covers Arabic academic writing conventions across major Arab university systems. Batch processing handles submission volumes. Evidence reports support instructor review. The tool functions as decision-support — providing evidence for human review, not automated sanctioning. Arab institutions should develop clear AI use policies aligned with their educational values and national AI governance frameworks. Detection results should contribute to investigation alongside other evidence — the student\'s writing history, class performance, interview if warranted — rather than serving as sole basis for consequential decisions.',
    },
    {
      category: 'professional',
      question: 'How does the detector support Arabic journalism and media?',
      answer: 'Arabic media organizations — Al Jazeera, Al Arabiya, major Arab print and digital newspapers — benefit from editorial screening for AI-generated content. Arabic journalistic genre calibration recognizes MSA journalistic conventions and avoids false positives for authentic professional Arabic journalism. API integration enables pre-publication screening workflows. For Islamic media and religious content publishers, specific calibration handles the classical register and Islamic scholarly writing conventions. Evidence reports identify flagged passages for efficient editorial review. The tool supports compliance with emerging Arab world regulatory frameworks around AI content transparency.',
    },
    {
      category: 'detection',
      question: 'How does the detector handle Islamic and religious Arabic content?',
      answer: 'Religious Arabic content — tafsir, fatwa, religious education materials — uses classical Arabic register and requires specific calibration for Islamic scholarly writing conventions. AI-generated Islamic content often reproduces surface Islamic vocabulary and formulaic phrases without authentic deep engagement with Islamic scholarly tradition. Detection for religious Arabic focuses on rhetorical authenticity signals: whether classical sources are cited and integrated as an authentic Islamic scholar would, whether Islamic legal reasoning follows authentic usul al-fiqh conventions, whether the text engages with Islamic scholarly tradition in ways that reflect genuine knowledge rather than surface Islamic vocabulary patterns. Religious Arabic detection is reported with explicit acknowledgment that technical detection cannot replace evaluation by qualified Islamic scholars.',
    },
    {
      category: 'general',
      question: 'What minimum Arabic text length is needed for reliable detection?',
      answer: 'Reliable Arabic AI detection requires approximately 150-200 words. Arabic\'s morphologically rich language and long average word length mean 150 Arabic words provide substantial linguistic signal. Below 100 words, low-confidence labeling applies. Diglossia analysis — assessing register appropriateness for context — requires sufficient text length to establish the register pattern throughout the text rather than in isolated sentences. For colloquial dialect analysis, longer texts provide more opportunities to assess authentic dialectal grammar versus pseudo-dialect vocabulary insertion. For highest-stakes decisions, 400+ word texts are recommended.',
    },
    {
      category: 'privacy',
      question: 'How is submitted Arabic content protected?',
      answer: 'All submitted content processes through encrypted channels with no persistent storage. Sessions are isolated with content cleared after analysis. No content is used for training without explicit consent. This matters for sensitive Arabic content contexts: academic submissions at Arab universities, confidential professional communications, journalistic content in pre-publication review, and religious content where confidentiality around scholarly opinions matters. Data residency options for Arab world users can locate all processing within specified geographic regions. PDPL (Saudi Arabia), PDPA (various Gulf states), and other Arab world data protection regulations inform the privacy architecture.',
    },
    {
      category: 'detection',
      question: 'Can the detector identify AI-generated Arabic by non-native Arabic writers?',
      answer: 'Non-native Arabic writers produce characteristic patterns from their native language backgrounds — English speakers show different transfer patterns than French speakers; Persian speakers show different patterns than Turkish speakers — that differ from AI generation signatures. The detector distinguishes non-native Arabic errors from AI generation through multi-signal analysis. Non-native Arabic shows transfer errors and learner patterns alongside authentic human content signals; AI Arabic shows systematic register and formality patterns alongside AI content signals. Low-proficiency Arabic learner writing receives lower-confidence labeling due to limited linguistic signal for reliable pattern analysis.',
    },
    {
      category: 'usage',
      question: 'How does the detector handle Arabic-English mixed content?',
      answer: 'Arabic-English mixed content is common in technical and professional Arabic writing, in Gulf region corporate communications, and in Arabic digital content. English technical terminology — especially in technology, science, and business — is standard in contemporary Arabic professional writing. The detector recognizes English terminology in appropriate Arabic professional contexts as authentic rather than AI signals. It assesses whether the Arabic-English mixing reflects authentic Arabic professional language use or AI-typical patterns of English insertion. For Arabizi (Arabic written in Latin characters with numbers for specific sounds), specialized processing is available with explicit lower-confidence labeling given the more limited calibration for this informal form.',
    },
    {
      category: 'technical',
      question: 'Does the Arabic AI Detector provide an API for institutional integration?',
      answer: 'Yes, the API enables integration into Arabic-language editorial, academic, and enterprise workflows. Endpoints accept Arabic Unicode text with optional parameters for intended variety (MSA, Egyptian, Levantine, Gulf, Maghrebi), register context, and content type. JSON responses include probability score, confidence bounds, variety classification, register appropriateness assessment, sentence-level analysis, and Arabic-specific feature reports. Batch endpoints support high-volume processing. Documentation is available in both Arabic and English. Webhook support enables workflow automation. Enterprise deployments support data residency requirements for Arab world regulatory compliance.',
    },
    {
      category: 'detection',
      question: 'How does the detector perform on Quran quotations and classical Arabic within modern texts?',
      answer: 'Quran quotations and classical Arabic passages within modern Arabic texts are correctly identified as authentic classical Arabic rather than AI signals. The detector\'s classical Arabic recognition layer distinguishes between classical source material (Quran, Hadith, classical scholarly texts) and the contemporary author\'s own writing. This distinction is important for Islamic scholarly writing where classical sources are extensively quoted and integrated. Patterns suggesting AI generation are assessed in the author\'s own analytical and discursive passages rather than in quoted classical material. The frequency and integration pattern of classical quotations is itself an authenticity signal assessed separately from classical text recognition.',
    },
    {
      category: 'general',
      question: 'How does the Arabic AI Detector stay current with improving Arabic AI capabilities?',
      answer: 'The detection model is updated quarterly against current AI outputs, with additional updates triggered by significant improvements in Arabic-language generation. Arabic AI capabilities have been advancing through both international AI platforms\' Arabic investments and through Arabic AI development in the Gulf, Egypt, and elsewhere. Each update benchmarks against the latest models\' Arabic outputs across both MSA and major dialect contexts, identifying new generation signatures and recalibrating detection thresholds. Colloquial dialect detection is updated as AI colloquial Arabic generation improves. Benchmark performance results are published after each update cycle.',
    },
    {
      category: 'regional',
      question: 'Why is Maghrebi Arabic (Darija) the clearest case for AI detection?',
      answer: 'Maghrebi Arabic varieties — Moroccan and Algerian Darija, Tunisian Arabic — are the most distinctive Arabic varieties from Middle Eastern Arabic, heavily influenced by French, Berber (Amazigh) languages, and their own phonological evolution. AI systems trained predominantly on Middle Eastern Arabic data are particularly poor at generating authentic Maghrebi colloquial, almost invariably producing either MSA or pseudo-Egyptian Arabic rather than authentic Darija. This means that authentic-looking Moroccan Darija or Tunisian Arabic in colloquial contexts is statistically very likely to be human-written, while AI-generated content claiming to be Maghrebi will show clear non-Maghrebi patterns. Maghrebi variety detection is one of the highest-confidence regional cases.',
    },
    {
      category: 'detection',
      question: 'What formal Arabic connectors does AI overuse?',
      answer: 'AI-generated MSA systematically overuses formal discourse connectors: "min hadha al-manthiq" (from this logic), "tajduru al-ishara ila anna" (it is worth noting that), "wa ala hadha al-asas" (and on this basis), "mima sabaq yattadih anna" (from what preceded it is clear that), "fi daw\' ma taqaddam" (in light of what preceded), and "wa khulasatu al-qawl" (to summarize) appear at formulaic intervals. Authentic Arabic writers use these connectors selectively, often preferring Arabic parataxis (juxtaposition without explicit connectors) or simpler Arabic transitions. The formulaic regularity of formal connector deployment — every paragraph beginning with a formal connector — is a reliable AI signal in Arabic academic and professional text.',
    },
    {
      category: 'accuracy',
      question: 'How does the detector handle code-switching between MSA and colloquial in the same text?',
      answer: 'MSA-colloquial code-switching is a legitimate authentic Arabic communication strategy used in various contexts — accessible journalism, popular education, social media, some types of literary writing. The detector distinguishes authentic code-switching (where the mixing reflects contextually purposeful register modulation) from AI pseudo-code-switching (where mixing reflects inconsistent AI register management). Authentic code-switching shows purposeful patterns: colloquial for dialogue or direct address, MSA for formal argument or quotation, with the switching calibrated to communicative goals. AI mixing tends to be more random, switching without apparent communicative rationale — this difference in switching pattern regularity and purposefulness is one of the more nuanced Arabic detection signals.',
    },
  ],
};



