import React from 'react';
import type { ToolContent } from '@/lib/tools/content/types';

const WriteUp = () => (
  <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:p-6 mt-10"><div className="prose prose-slate max-w-none">
    <h2 className="text-2xl font-bold text-slate-900 mb-4">French AI Detector: Identify AI-Generated Text in French with Precision</h2>
    <p className="text-slate-700 mb-4">Detecting AI-generated text in French presents unique challenges that English-focused detection tools consistently fail to address. French has distinct grammatical structures, stylistic conventions, and rhetorical traditions that create language-specific AI signatures — patterns that AI systems generate when writing in French that differ meaningfully from how AI detection plays out in English. A detector trained primarily on English text will misidentify authentic French literary and academic writing as AI-generated, while simultaneously missing AI-generated French text that follows French-language patterns not represented in English training data. The French AI Detector is purpose-built for French-language content, trained on extensive French corpora spanning formal academic writing, professional communications, journalism, creative literature, and informal digital content.</p>
    <p className="text-slate-700 mb-4">French poses specific detection challenges because of its grammatical complexity and formal register traditions. French academic and professional writing has long favored elaborate sentence structures, sophisticated subordinate clauses, and formal connective language — patterns that overlap significantly with AI-generated text signatures in English detection frameworks. A French doctoral student writing in the established tradition of French academic prose may use Latinized vocabulary, complex periodic sentences, and abstract nominalization at rates that English-language detectors flag as AI-generated — when in fact this is precisely how French academic writing is taught and expected. The French AI Detector is calibrated against authentic French writing across all registers and formality levels, avoiding the systematic false positive problem that afflicts English-language tools applied to French content.</p>
    <p className="text-slate-700 mb-4">Conversely, AI systems writing in French exhibit patterns that a French-trained detector reliably identifies. AI-generated French tends to overuse formal transition phrases (en outre, par conséquent, il convient de noter) with greater frequency and less contextual appropriateness than authentic French writers. AI French shows characteristic nominalization patterns — converting verbs to abstract nouns — beyond the degree that even formal French academic writing employs. AI French often produces the stylistic variety of registers inconsistently, mixing very formal constructions with informal elements in ways that authentic French writers rarely do. These French-specific AI signatures require French-specific detection capability.</p>

    <h3 className="text-xl font-semibold text-slate-800 mb-3">French Language AI Signatures: What the Detector Identifies</h3>
    <p className="text-slate-700 mb-4">AI-generated French text exhibits several characteristic patterns across different AI systems. The most reliable detector signal is what French linguistics researchers call "sur-nominalisation artificielle" — excessive nominalization that converts action-oriented verb phrases into abstract noun constructions beyond what stylistically conscious French writers do. Where a human French writer might write "nous avons analysé les données" (we analyzed the data), AI frequently produces "nous avons procédé à l&#39;analyse des données" (we proceeded to the analysis of the data) — a nominalized construction that feels bureaucratic and removes agency. The systematic preference for this construction throughout a text, rather than its selective use for emphasis, is a reliable AI signal.</p>
    <p className="text-slate-700 mb-4">Connector overuse is a second major French AI signature. French has a rich inventory of discourse connectors — transition phrases, logical connectives, and sequential markers — and French AI systems apply them with systematic regularity that exceeds authentic French writing patterns. Phrases like "dans ce contexte," "il importe de souligner," "force est de constater," and "à cet égard" appear in AI-generated French with high frequency and formulaic placement. Human French writers use these connectors selectively, often preferring simple parataxis or implicit logical connections. When these formal connectors appear at every paragraph boundary and at regular intervals within paragraphs, the pattern indicates AI authorship rather than human stylistic choice.</p>
    <p className="text-slate-700 mb-4">Register inconsistency is particularly telling in French because French has a more elaborated formal/informal distinction than English. Authentic French writers — even professional ones writing formally — maintain relatively consistent register throughout a document, with marked transitions when they shift. AI-generated French often mixes très soutenu (very formal) constructions with standard or even familiar register elements in the same passage, reflecting training data that mixed French text from different register contexts. The French AI Detector&#39;s register analysis identifies these inconsistency patterns as a high-confidence AI signal.</p>
    <p className="text-slate-700 mb-4">Idiomatic authenticity is another detection dimension. French has a rich idiomatic tradition, and authentic French writers naturally incorporate expressions, proverbs, and colloquially understood phrases that reflect genuine French language immersion. AI-generated French tends toward grammatically correct but idiomatically sterile language — correct in every rule-following respect but missing the natural idiomatic expressions that native and fluent French writers use. This absence of idiomatic naturalness, detectable through comparison against French idiomatic frequency patterns, is a reliable AI indicator, particularly for content claiming to represent a French native voice.</p>

    <h3 className="text-xl font-semibold text-slate-800 mb-3">Academic French Detection: Universities and Research Institutions</h3>
    <p className="text-slate-700 mb-4">French universities and grandes écoles face a particular detection challenge because French academic writing tradition already employs many stylistic features that overlap with AI generation patterns. The dissertation française, the synthèse de documents, and the commentaire composé — standard French academic writing forms — involve elaborate formal structure, extensive use of logical connectives, and abstract vocabulary that English-language AI detectors consistently flag as AI-generated when the writing is entirely authentic. French institutions using generic AI detection tools have reported unacceptably high false positive rates on student submissions, with one study finding that the French dissertation format produced false positive rates exceeding 40% on standard English-centric tools.</p>
    <p className="text-slate-700 mb-4">The French AI Detector addresses this by calibrating against authentic French academic writing samples from each major academic genre. The detector&#39;s academic calibration mode recognizes when it&#39;s analyzing a dissertation, a synthèse, a commentaire, or a research article, and adjusts its thresholds accordingly — recognizing that a certain level of formal connector use, nominalization, and abstract vocabulary is appropriate and expected for the specific genre. Only patterns that exceed genre-appropriate norms trigger detection alerts, dramatically reducing false positive rates while maintaining sensitivity to genuine AI generation that goes beyond even the conventions of formal French academic writing.</p>
    <p className="text-slate-700 mb-4">Research article detection presents different challenges. French academic journals, particularly in humanities and social sciences, maintain distinctive disciplinary writing styles that have evolved over decades. Sociology, philosophy, linguistics, and literary criticism in French have characteristic vocabulary, argument structures, and citation conventions that differ from both English-language academic writing and from the French academic writing in other disciplines. The detector&#39;s discipline-specific calibration recognizes these distinctions, enabling accurate detection in specialized academic French contexts where generic detection tools fail.</p>

    <h3 className="text-xl font-semibold text-slate-800 mb-3">Professional French Content Detection</h3>
    <p className="text-slate-700 mb-4">Professional French communication encompasses an enormous range of contexts, from formal legal and administrative documents to commercial communications, journalism, and public affairs. Each context has its own conventions, and AI generation in professional contexts tends to produce text that is generically professional rather than appropriately genre-specific. A legal document written by AI in French may be formally correct but may lack the precise legal terminology patterns, the specific clause structures, and the genre-appropriate document architecture that French legal professionals use. A journalistic article written by AI in French may be well-structured but may lack the stylistic signatures of specific French journalistic traditions.</p>
    <p className="text-slate-700 mb-4">Corporate communications in French benefit particularly from AI detection capability. French multinational corporations and French subsidiaries of international companies increasingly use AI to generate French-language content for clients, partners, and employees. Authenticating that high-stakes communications — board letters, executive messages, important client communications — represent genuine human authorship rather than AI generation is a growing governance concern. The detector supports corporate compliance use cases through batch processing of document collections and API integration with document management systems, enabling systematic authentication workflows at scale.</p>
    <p className="text-slate-700 mb-4">Journalistic applications are increasingly important as French media organizations grapple with AI content disclosure standards. The French press council and major publication groups have been developing AI content transparency guidelines that require identification of AI-generated elements in published content. The French AI Detector supports editorial teams in identifying AI-generated submissions and flagging content for additional review, helping publications comply with emerging transparency standards. The detector is calibrated against the specific writing styles of major French journalistic genres — newspaper articles, magazine features, editorial commentary, cultural reviews — enabling appropriate genre-sensitive detection.</p>

    <h3 className="text-xl font-semibold text-slate-800 mb-3">Regional Varieties of French: Québécois, Belgian, and Francophone African French</h3>
    <p className="text-slate-700 mb-4">French is spoken as a primary language by over 300 million people across France, Québec, Belgium, Switzerland, and numerous African nations, each with distinct linguistic varieties that create detection challenges for tools trained only on Metropolitan French. Québécois French has distinctive vocabulary, phonological influences on written style, and grammatical constructions that differ from European French and that AI systems don&#39;t always reproduce accurately. A Québécois writer produces different French than a Parisian writer — not just in vocabulary choices but in sentence rhythm, rhetorical approach, and idiomatic preferences. A detector trained only on Metropolitan French will generate false positives for authentic Québécois writing.</p>
    <p className="text-slate-700 mb-4">Belgian French occupies a distinctive space between Metropolitan French and Flemish influence, with specific lexical items (septante, nonante for seventy and ninety), specific administrative vocabulary, and writing traditions shaped by the bilingual Belgian context. Swiss French similarly has regional vocabulary and a writing culture influenced by the multilingual Swiss federal environment. Francophone African French varieties — from Senegalese French to Congolese French to Moroccan Darija-influenced French — reflect local linguistic substrates, code-switching patterns, and rhetorical traditions that distinguish them from European French norms.</p>
    <p className="text-slate-700 mb-4">The French AI Detector&#39;s multi-variety calibration recognizes these regional distinctions. When analyzing text that exhibits Québécois, Belgian, or Francophone African French characteristics, the detector applies variety-appropriate calibration rather than flagging authentic regional French as AI-generated based on Metropolitan French norms. This regional sensitivity is important both for accuracy (avoiding false positives for authentic regional writing) and for detection coverage (recognizing that AI systems producing regional French varieties exhibit different patterns than AI producing Metropolitan French, and both need appropriate detection frameworks).</p>

    <h3 className="text-xl font-semibold text-slate-800 mb-3">Accuracy, False Positives, and Calibration</h3>
    <p className="text-slate-700 mb-4">False positive management is the central challenge for any AI detection tool applied to French content. The systematic overlap between French formal writing conventions and AI generation patterns means that calibration matters more for French than for any other major European language. The French AI Detector maintains comprehensive calibration benchmarks across French writing genres, formality levels, regional varieties, and author expertise levels, and reports detection confidence levels that account for genre-specific baseline norms rather than applying uniform thresholds across all French text.</p>
    <p className="text-slate-700 mb-4">The detector reports results on a probability spectrum with explicit uncertainty bounds rather than binary AI/human classifications. Text scoring 85%+ probability of AI generation with narrow confidence intervals is flagged as high-confidence AI. Text scoring 60-85% is flagged for review — likely AI but requiring human judgment given ambiguity. Text below 60% receives a human-probable classification, with scores in the 40-60% range flagged as ambiguous. This probability spectrum approach is more honest about detection uncertainty than binary classification, particularly important for the formal French writing contexts where genuine uncertainty is highest.</p>
    <p className="text-slate-700 mb-4">Continuous calibration updates keep the detector current with evolving AI French generation capabilities. As AI systems improve their French writing quality and introduce new generation patterns, the detector&#39;s training is updated against current AI outputs. As human French writing evolves — particularly with the influence of digital communication on formal writing norms — the human baseline calibration is also updated. Users on the platform automatically receive updated model versions without any action required, ensuring detection remains current without requiring user-managed updates.</p>

    <h3 className="text-xl font-semibold text-slate-800 mb-3">Technical Architecture and Integration</h3>
    <p className="text-slate-700 mb-4">The French AI Detector&#39;s technical architecture combines multiple detection approaches that each address different AI signature types. A linguistic feature extractor identifies structural patterns — sentence length distributions, connector frequencies, nominalization rates, register consistency — that form the foundation of the detection signal. A semantic coherence analyzer assesses whether meaning relationships across the text reflect human-authentic associative patterns or AI-typical systematic coherence. A style fingerprinting module compares the text&#39;s stylistic profile against both authentic French human writing samples and known AI output samples to generate probability scores.</p>
    <p className="text-slate-700 mb-4">The API enables integration into existing editorial, academic, and enterprise workflows. Content management systems, learning management platforms, and document processing pipelines can connect to the detection API and receive structured JSON responses including probability scores, confidence bounds, detected AI-signal passages, and genre classification. Batch processing supports analysis of large document collections — semester-end assignment batches, archive review projects, content library audits — without requiring individual manual submissions. Webhook support allows integration with downstream workflows that trigger based on detection results.</p>
  </div>
</section>
);

export const frenchAiDetectorContent: ToolContent = {
  writeUp: <WriteUp />,
  faqs: [
    {
      category: 'general',
      question: 'Why do I need a French-specific AI detector rather than a general one?',
      answer: 'General AI detectors trained primarily on English text produce unacceptably high false positive rates on authentic French writing — particularly formal academic and professional French, which shares structural features with AI generation patterns that English-centric models flag incorrectly. Studies find that standard French academic writing formats like the dissertation française produce false positive rates exceeding 40% on English-centric tools. Simultaneously, generic detectors miss French-specific AI signatures — the characteristic nominalization patterns, connector overuse, and register inconsistencies that distinguish AI-generated French from human-written French. A French-specific detector calibrated against authentic French writing across all registers provides dramatically better accuracy for both false positive reduction and true positive detection.',
    },
    {
      category: 'detection',
      question: 'What specific patterns does the French AI Detector look for?',
      answer: 'The detector identifies several French-specific AI signatures. Excessive nominalization — converting verbs to abstract noun constructions beyond what even formal French writers do ("procédé à l\'analyse" instead of "analysé"). Systematic connector overuse — formal transition phrases like "dans ce contexte," "il convient de souligner," and "force est de constater" appearing with formulaic regularity at every paragraph boundary. Register inconsistency — mixing très soutenu formal constructions with standard or informal elements in the same passage. Idiomatic sterility — grammatically correct French that lacks the natural idiomatic expressions native and fluent French writers use. These signals in combination yield high-confidence AI attribution.',
    },
    {
      category: 'academic',
      question: 'How does the detector handle formal French academic writing without false positives?',
      answer: 'The detector\'s academic calibration mode recognizes specific French academic genres — dissertation, synthèse de documents, commentaire composé, research article — and adjusts detection thresholds to account for genre-appropriate formal conventions. A certain level of formal connectors, nominalization, and abstract vocabulary is expected and appropriate in French academic writing; the detector only flags patterns that exceed genre-appropriate norms, not patterns that conform to them. This genre-aware calibration reduces false positive rates dramatically compared to generic tools. Discipline-specific calibration further distinguishes between humanities, social sciences, and STEM academic French, each with different conventions.',
    },
    {
      category: 'regional',
      question: 'Does the detector handle Québécois, Belgian, and African French varieties?',
      answer: 'Yes, multi-variety calibration covers major regional French varieties. When text exhibits Québécois, Belgian, or Francophone African French characteristics — regional vocabulary, distinctive grammatical constructions, variety-specific rhetorical patterns — the detector applies variety-appropriate calibration rather than flagging authentic regional writing based on Metropolitan French norms. Regional French varieties have different structural characteristics and different AI generation patterns (AI systems often produce less authentic regional variety when targeting non-Metropolitan French) requiring separate calibration for both accurate false positive avoidance and accurate AI detection in regional contexts.',
    },
    {
      category: 'general',
      question: 'What types of French content can the detector analyze?',
      answer: 'The detector handles all French text types: academic writing (dissertations, research articles, theses), professional documents (legal texts, business communications, reports), journalism (newspaper articles, magazine features, editorial commentary), creative content (fiction, essays, poetry), educational content (student essays, course materials), and digital content (web articles, social media posts, marketing copy). Each content type has calibration-specific thresholds reflecting genre conventions. The detector performs best on texts of 200+ words where sufficient linguistic context is available for reliable pattern analysis. Very short texts (under 100 words) receive lower-confidence assessments with explicit uncertainty reporting.',
    },
    {
      category: 'accuracy',
      question: 'What is the detection accuracy for French AI content?',
      answer: 'The detector achieves approximately 89% true positive rate (correctly identifying AI-generated French) and approximately 91% true negative rate (correctly identifying human-written French) on benchmark test sets covering diverse French text types and AI sources. Performance varies by text type: academic formal French shows highest accuracy (both directions) due to the distinct genre conventions. Informal and creative French shows somewhat lower accuracy where human and AI writing overlap more. These benchmarks are regularly updated as AI systems improve their French generation capabilities. The probability-spectrum output (rather than binary classification) enables users to make appropriate decisions based on confidence levels rather than treating all positive detections as equally certain.',
    },
    {
      category: 'academic',
      question: 'Can French universities use this tool for academic integrity?',
      answer: 'Yes, the tool is specifically designed for academic integrity applications and includes features needed for institutional deployment. Batch processing handles semester-end submission volumes. LMS integration connects with Moodle, Blackboard, and Canvas through the API. Detailed evidence reports explain why specific passages were flagged, supporting instructor review decisions. Instructor dashboard provides class-level analytics on submission patterns. The tool is designed as a decision-support system rather than an automated sanctioning system — it provides evidence for human review rather than automatically flagging submissions for disciplinary action. Institutions should implement clear AI use policies and ensure students understand detection is in use.',
    },
    {
      category: 'professional',
      question: 'How does the detector support French media and journalism?',
      answer: 'The detector supports editorial workflows through real-time analysis of submitted content and batch analysis of content archives. Genre calibration for major French journalistic formats — article de presse, reportage, éditorial, critique culturelle — ensures detection is appropriate for specific publication contexts. Integration with content management systems enables automatic pre-publication screening. For compliance with emerging French press council guidelines on AI content transparency, the detector provides the documentation needed to support disclosure decisions. The evidence report identifies specific passages with elevated AI probability, enabling editors to review flagged content efficiently rather than rereading entire submissions.',
    },
    {
      category: 'technical',
      question: 'Does the French AI Detector offer an API for integration?',
      answer: 'Yes, the API enables integration into editorial, academic, and enterprise workflows. Endpoints accept French text and optional parameters including genre classification, regional variety specification, and formality level context. JSON responses include overall probability score, confidence bounds, sentence-level probability scores, detected AI-signal features with explanations, and genre classification confirmation. Batch endpoints process multiple documents simultaneously for large-scale workflows. Webhook support enables downstream workflow triggers based on detection results. Rate limits are configurable for integration tier. Documentation covers authentication, parameter specifications, response schemas, and code examples in Python, JavaScript, and common integration languages.',
    },
    {
      category: 'general',
      question: 'Can the detector identify which AI model wrote a French text?',
      answer: 'The detector can attribute French AI text to source models with varying confidence depending on model-specific signature distinctiveness. GPT-4 and GPT-5 series models have relatively distinctive French writing signatures, particularly around specific connector preferences and nominalization patterns, enabling moderate-confidence attribution. Claude\'s French outputs have different but also distinctive patterns. Gemini French outputs exhibit characteristics of Google\'s training data. However, model attribution is significantly less reliable than AI vs. human classification, and the detector presents model attribution as a secondary analysis with explicit low-confidence labeling. As AI models continue to improve and converge in quality, model attribution confidence decreases — the primary value is AI vs. human classification rather than specific source attribution.',
    },
    {
      category: 'accuracy',
      question: 'What should I do if I think the detector incorrectly flagged human-written French?',
      answer: 'If you believe a detection result is a false positive, several steps are helpful. First, review the evidence report identifying which specific passages triggered detection alerts — this pinpoints exactly what the detector found unusual about the text. If the flagged passages reflect a distinctive personal writing style, domain-specific vocabulary, or genre conventions not well-represented in the detector\'s training data, this is useful feedback. Second, the tool offers a "context submission" feature where you can provide additional context about the author, genre, and writing context to enable a re-analysis with that context. Third, if you have samples of the same author\'s other writing, comparing detection scores across samples can reveal whether the flagging is consistent or isolated. False positives in formal, academic, or highly specialized French contexts should be reviewed with professional judgment.',
    },
    {
      category: 'detection',
      question: 'Does the detector handle mixed French-English (code-switching) content?',
      answer: 'Yes, code-switching between French and English appears frequently in Québécois digital content, professional contexts in Canada, and technical writing where English terminology is standard. The detector handles mixed-language content by analyzing the French-language segments with French calibration and recognizing that code-switching itself is a marker of authentic French communication in specific contexts — AI-generated text tends to either code-switch less than authentic writers in code-switching contexts or code-switch with less naturalistic patterns. Extensive English terminology in technical French writing (computer science, medicine, finance) is handled through domain-specific calibration that treats expected borrowing as neutral rather than as an AI signal.',
    },
    {
      category: 'professional',
      question: 'Is the French AI Detector useful for content marketing teams?',
      answer: 'Yes, content marketing teams managing French-language content benefit from AI detection for several reasons. Quality assurance: ensuring that content produced by freelancers or agencies represents authentic human authorship as claimed. Compliance: meeting platform AI content disclosure requirements on LinkedIn, Medium, and other platforms with AI content policies. Competitive intelligence: analyzing competitor French content to understand whether they\'re using AI generation. Performance benchmarking: correlating content authenticity scores with engagement metrics to understand whether human-authentic French content outperforms AI-generated content for specific audience segments. The batch processing API enables integration into content management workflows at scale.',
    },
    {
      category: 'technical',
      question: 'How does the detector handle French text with specialized technical vocabulary?',
      answer: 'Technical French — legal terminology, medical French, scientific writing, financial language — presents detection challenges because specialized vocabulary is constrained by field conventions, making it appear lower-variance than general French writing. The detector\'s domain calibration handles major technical domains by adjusting perplexity and vocabulary diversity thresholds to account for the constrained vocabulary of specialized fields. Legal French, for example, is expected to use specific formulaic phrases and technical terms — the detector doesn\'t flag these as AI signals. Instead, it focuses on the non-technical structural patterns — sentence architecture, logical connectives, text organization — that still differ between AI-generated and human-written technical French.',
    },
    {
      category: 'general',
      question: 'How does the French AI Detector stay current with new AI writing capabilities?',
      answer: 'The detector\'s training is updated in response to AI system improvements and new French-language model releases. Each major AI update that changes French writing quality or introduces new generation patterns triggers a retraining cycle. The detector is benchmarked against current AI outputs quarterly, and calibration is adjusted when benchmark performance on new AI models drops below acceptable thresholds. Users automatically receive updated models without action required. The benchmark performance page shows current accuracy metrics against each major AI system\'s French outputs, updated after each retraining cycle, so users can assess current detection capability before using the tool for high-stakes decisions.',
    },
    {
      category: 'privacy',
      question: 'Is submitted French content kept private?',
      answer: 'All submitted content is processed through encrypted channels with no persistent storage of analyzed text. Each session is isolated, with submitted text cleared from processing queues after analysis is complete. No submitted content is used for model training or improvement without explicit consent. This privacy approach is important for the sensitive contexts where French AI detection is often needed — academic submissions, confidential professional documents, journalistic content in pre-publication review. Enterprise deployments offer on-premise processing options for organizations with strict data residency requirements, keeping all analysis within organizational infrastructure with no external data transmission.',
    },
    {
      category: 'accuracy',
      question: 'How does the detector perform on very formal French government documents?',
      answer: 'French government and administrative writing represents one of the most challenging detection contexts because official French administrative style (le style administratif) is itself highly formulaic, connector-heavy, and nominalized — overlapping substantially with AI generation patterns. The detector has specific administrative French calibration that accounts for the distinctive features of French official writing: specific administrative connectors, standardized document structures, formulaic opening and closing conventions. Within administrative style, detection focuses on micro-level patterns that AI systems get wrong even when trying to imitate administrative French — specific register combinations, formula usage patterns that deviate slightly from authentic administrative conventions, and the subtle semantic fluency that longtime administrative writers achieve.',
    },
    {
      category: 'usage',
      question: 'What is the minimum text length for reliable French AI detection?',
      answer: 'Reliable detection requires a minimum of approximately 150-200 words of continuous French text. Below this threshold, the detector has insufficient linguistic context to reliably assess the statistical patterns that distinguish AI from human French writing. For texts between 100-200 words, results are reported with low-confidence labels and wider probability intervals. For texts above 200 words, confidence increases progressively with length — a 500-word text produces more reliable results than a 250-word text. For the highest-stakes decisions, texts of 800+ words provide the most reliable detection results. When analyzing short texts for important purposes, aggregating detection results across multiple related short texts (rather than relying on a single short text analysis) improves reliability.',
    },
    {
      category: 'detection',
      question: 'Can the detector identify AI-paraphrased or AI-edited French text?',
      answer: 'AI-paraphrased text — human writing that has been passed through an AI to rephrase or rewrite — presents the hardest detection challenge because it combines human content with AI stylistic transformation. Lightly AI-edited text (minor corrections, word substitutions) is typically not detectable as AI-generated. Substantially AI-rewritten text (AI paraphrase of human content) shows partial AI signatures that the detector identifies with moderate confidence — scoring in the 50-70% range rather than the 85%+ range typical of fully AI-generated text. These partial-AI scores are reported with explicit notes about possible AI-editing rather than full AI generation. The French AI Detector is most reliable for identifying fully AI-generated French text and least reliable for identifying lightly AI-edited human French text.',
    },
    {
      category: 'academic',
      question: 'How should French institutions implement AI detection policies?',
      answer: 'Effective institutional implementation requires several components. First, clear written policies that define permitted and prohibited AI use, communicated to students before assignments are given. Second, detection as a decision-support tool rather than automated sanctioning — all flagged submissions should receive human review before any disciplinary action. Third, calibration education for instructors about what detection scores mean and what they don\'t mean — a 70% AI probability score is not proof of AI use but is a signal warranting investigation. Fourth, an appeals process for students who believe detection results are incorrect. Fifth, acknowledgment that detection tools are imperfect and that detection alone should not be the basis for serious disciplinary action without additional evidence. The French AI Detector is designed to support this human-centered approach rather than replace human judgment.',
    },
    {
      category: 'general',
      question: 'What languages beyond French does the platform support?',
      answer: 'The platform offers dedicated AI detectors for 20+ languages including German, Spanish, Italian, Portuguese, Dutch, Russian, Arabic, Chinese, Japanese, Korean, Hindi, and Indonesian. Each language detector is independently trained and calibrated for that language\'s specific AI signature patterns and authentic writing conventions. Users working with multilingual content can run language-specific detection on each language segment rather than applying a single generic multilingual detector. The French AI Detector is the French-specific component of this broader multilingual detection suite. Users managing multilingual content programs benefit from consistent cross-language detection methodology with language-appropriate calibration in each language.',
    },
    {
      category: 'professional',
      question: 'Can the French AI Detector be used for legal documents and contracts?',
      answer: 'Yes, with appropriate context about legal French\'s distinctive conventions. Legal French is highly formalized with specific terminology, standardized clause structures, and conventional phrasing that the detector\'s legal domain calibration accounts for. Detection in legal contexts focuses on patterns that go beyond legal convention: structural choices that deviate from the specific conventions of the relevant legal genre (contract vs. legal opinion vs. court filing vs. regulatory submission), terminology combinations that don\'t reflect authentic legal practice in the relevant jurisdiction, and the subtle fluency markers that distinguish lawyers trained in French legal tradition from AI systems producing formally correct but experientially inauthentic French legal writing.',
    },
    {
      category: 'usage',
      question: 'How do I interpret the detector\'s probability scores?',
      answer: 'The detector reports probability on a 0-100% scale where 100% indicates certainty of AI generation. Scores above 85% with narrow confidence intervals represent high-confidence AI detection — the text exhibits multiple strong AI signatures consistently throughout. Scores of 60-85% represent probable AI with meaningful uncertainty — worth investigating but not conclusive. Scores of 40-60% are genuinely ambiguous — the text has some AI-like characteristics but also human-authentic features, which could indicate AI-assisted human writing, a human writer whose style resembles AI patterns, or genuine uncertainty. Scores below 40% indicate probable human authorship. For institutional or professional decisions, scores above 85% warrant investigation; scores below 60% should generally not be acted upon without additional evidence.',
    },
    {
      category: 'technical',
      question: 'Does the detector analyze French text at the sentence level or document level?',
      answer: 'The detector analyzes at both levels and reports both views. Document-level analysis provides the overall probability score and genre classification. Sentence and paragraph-level analysis highlights specific passages that contributed most strongly to the detection score — the passages where AI signatures are most concentrated. This dual-level analysis is particularly useful for identifying partially AI-generated documents (where some sections were human-written and some were AI-generated) and for pinpointing specifically which passages need closest human review. The sentence-level heat map visualization makes it easy to see at a glance where AI signals are concentrated in a document rather than just knowing an overall score.',
    },
    {
      category: 'accuracy',
      question: 'How does the detector perform on AI text that has been manually edited?',
      answer: 'Detection performance degrades proportionally to the extent of human editing applied to AI-generated text. Lightly edited AI text (a few word changes, punctuation corrections) typically retains 80-90% of its original AI probability score. Moderately edited AI text (paragraph-level restructuring, significant word substitution, added personal examples) typically scores 50-70%, depending on how extensively the AI structure was modified. Heavily edited AI text that reads as primarily the human editor\'s work rather than the AI\'s original output typically scores below 50% and may score as human-probable. This degradation is unavoidable — a document that has been substantially rewritten by a human is substantially human-written and should score accordingly. The detector accurately reflects the degree of human vs. AI authorship in edited documents.',
    },
  ],
};



