import React from 'react';
import type { ToolContent } from '@/lib/tools/content/types';

const WriteUp = () => (
  <section className="rounded-2xl border-3 border-black bg-white p-4 shadow-neo-sm md:p-6 mt-10"><div className="prose prose-slate max-w-none">
    <h2 className="text-2xl font-bold text-slate-900 mb-4">Indonesian AI Detector: Spot AI-Generated Bahasa Indonesia Content</h2>
    <p className="text-slate-700 mb-4">Indonesian (Bahasa Indonesia) exhibits a unique AI detection profile among major global languages. Unlike Japanese, Korean, or Arabic, Indonesian features relatively straightforward morphology and lacks an elaborate honorific system—traits that might imply easy AI generation of authentic text. The detection challenge for Indonesian resides elsewhere: within the gap between formal Indonesian (bahasa baku) and the informal Indonesian actually spoken in daily communication, the profound influence of regional languages (Javanese, Sundanese, Batak, Minang, and numerous others) on genuine Indonesian writing, and the rapid evolution of Indonesian internet slang (bahasa gaul) that AI models poorly approximate. These Indonesian-specific traits create detectable AI signatures demanding Indonesian-specific detection capabilities.</p>
    <p className="text-slate-700 mb-4">Indonesia stands as the world&#39;s fourth most populous nation hosting over 270 million inhabitants, and Bahasa Indonesia experiences rapid digital growth as internet penetration reaches hundreds of millions of Indonesian speakers. Indonesia&#39;s university system supports approximately 9 million enrolled learners across upwards of 4,000 higher education institutions. Indonesian digital media, e-commerce platforms, social media networks, and the creator economy produce massive volumes of Bahasa Indonesia content. AI tool adoption within Indonesia has surged swiftly, with Indonesian-capable AI tools widely reachable for students, professionals, and content creators—rendering Indonesian AI detection capabilities increasingly vital across institutional and commercial sectors.</p>
    <p className="text-slate-700 mb-4">The primary detection challenge for Indonesian centers on the formal-informal register gap. Formal Indonesian writing (bahasa formal/baku) serves academic papers, official paperwork, news journalism, and formal professional correspondence. Informal Indonesian (bahasa informal) utilized in everyday dialogue, social media, and casual digital messaging varies markedly—employing contracted forms, regional borrowings, English loanwords, and colloquialisms characteristic of authentic Indonesian digital expression. AI-generated Indonesian defaults to formal bahasa baku regardless of context, yielding text that reads rigidly and artificially in casual settings where genuine Indonesians would employ informal registers. This register mismatch functions as the most reliable Indonesian AI detection signal.</p>

    <h3 className="text-xl font-semibold text-slate-800 mb-3">Local Indonesian Patterns of Artificial Intelligence Generation</h3>
    <p className="text-slate-700 mb-4">The prefix-suffix morphology of Indonesian generates a distinct AI detection signal. Indonesian employs a rich system of affixes—prefixes (me-, ber-, di-, ke-, ter-, pe-), suffixes (-kan, -i, -an), and circumfixes (ke-an, per-an, pe-an)—each modifying root word meanings in precise ways. Genuine Indonesian authors apply these affixes using intuitions cultivated over years of language practice, choosing the fitting affixed form for every context. AI-generated Indonesian occasionally applies affixes incorrectly—selecting an inappropriate prefix for the verb's transitivity type, employing passive di- forms where active me- forms feel more natural, or consistently picking the identical affixed form across varied contexts where authentic Indonesian would vary the structure.</p>
    <p className="text-slate-700 mb-4">[1] The impact of local dialects on standard Indonesian represents a deeply cultural dimension of Indonesian AI recognition. The hundreds of native tongues across Indonesia shape the written Indonesian of authors hailing from distinct territories — Javanese markers in Central Java's writing, Sundanese touches in West Java prose, Minang elements in Sumatran text, and beyond. Such geographical effects remain subtle within formal prose yet show up clearly through word selection, idiomatic turns, and stylistic choices. Machine-created Indonesian misses true regional language substrate traces, yielding a standard form that discerning locals easily spot as lacking the genuine regional color typical of copy penned by native Indonesian authors from specific areas.</p>
    <p className="text-slate-700 mb-4">[2] Indonesian internet slang (bahasa gaul) features a vibrant lexicon consisting of abbreviations, informal terms, and creative orthography that AI models struggle to replicate accurately. Expressions including gue/gw (casual first person), lu/lo (casual second person), nggak/ngga (casual negation), alongside numerous contemporary slang items define genuine informal Indonesian online communication. Indonesian social media language encompasses unique shortened forms for standard phrases, inventive spelling styles (omitting specific letters, phonetic spelling), and a mix of formal Indonesian, regional loanwords, and English found in real Indonesian digital media. AI-crafted casual Indonesian frequently replaces these informal expressions with standard counterparts, creating stiff digital text.</p>

    <h3 className="text-xl font-semibold text-slate-800 mb-3">[3] Indonesian Academic Writing Detection</h3>
    <p className="text-slate-700 mb-4">[4] Indonesian scholarly writing bears deep marks from Dutch academic traditions originating in colonial times, American academic styles through post-independence student exchanges, and the unique demands of local higher education facilities. Formal Indonesian academic prose (bahasa ilmiah) employs standard bahasa baku featuring specialized academic vocabulary, citation methods adhering to local academic group rules (such as MPKI), and logical argumentation frameworks mirroring domestic scholarly culture alongside its varied roots. AI-generated Indonesian scholarly prose delivers grammatically correct bahasa baku fulfilling baseline criteria yet missing the precise rhetorical genuineness reflecting true connection to Indonesian intellectual heritage.</p>
    <p className="text-slate-700 mb-4">[5] The skripsi (bachelor thesis), tesis (master thesis), and disertasi (doctoral dissertation) form the main Indonesian academic writing categories. Every single one features precise structural demands and stylistic expectations set by DIKTI (Directorate General of Higher Education) rules. Numerous Indonesian universities enforce unique layout rules surpassing standard DIKTI instructions. AI-produced skripsi or tesis documents occasionally rely on broad academic writing traditions instead of Indonesia-focused academic formatting rules, exposing unfamiliarity with local higher education composition norms. This compliance review proves especially valuable for local academic honesty initiatives.</p>
    <p className="text-slate-700 mb-4">[6] Indonesian high school and middle school composition — SMA (high school) papers and SMP (middle school) tasks — follows distinct rules shaped by the Bahasa Indonesia language education syllabus. The local schooling network highlights particular formal composition rules that pupils practice heavily, generating an authentic local pupil writing profile diverging from AI-made formal Indonesian in clear ways. Screening for secondary schooling environments demands calibration against the genuine span of student writing standards instead of applying university-level scholarly writing standards.</p>

    <h3 className="text-xl font-semibold text-slate-800 mb-3">[7] Indonesian Digital Content and Media Detection</h3>
    <p className="text-slate-700 mb-4">[8] Indonesian digital media expanded dramatically alongside the country's fast-growing internet availability, with domestic content production covering news outlets, social networks, online shopping reviews, and creator economy networks. Detik, Kompas, Tribun, and major local news networks each maintain unique editorial tones. Indonesian YouTube, TikTok, and Instagram influencer communities display specific interaction customs. AI-made Indonesian material for these networks regularly fails to capture precise platform norms and the genuine Indonesian tone expected by online audiences.</p>
    <p className="text-slate-700 mb-4">[9] Indonesian online retail ranks among the most active globally, with platforms like Tokopedia, Shopee, and Bukalapak producing massive amounts of domestic product descriptions, reviews, and vendor messaging. AI-produced merchandise descriptions in Indonesian frequently deliver excessively formal bahasa baku for a setting demanding persuasive informal-register marketing Indonesian. Detection for local e-commerce settings supports marketplace originality standards and aids online retail managers in spotting machine-made vendor text that might not mirror actual human seller experiences.</p>

    <h3 className="text-xl font-semibold text-slate-800 mb-3">[10] Technical Features and Integration</h3>
    <p className="text-slate-700 mb-4">[11] Indonesian utilizes the Latin script, simplifying certain technical tasks compared to Arabic or Japanese writing systems. The language's fairly consistent spelling rules make tokenization straightforward. The technical hurdle for Indonesian evaluation centers on morphology: the affix system demands spotting base words and their attachments, where the usage pattern of these attachments acts as a primary detection marker. Indonesian morphological review spots bases and affixed variations, permitting analysis of affix application naturalness. The system additionally handles Indonesian-English code-switching, frequent in local digital and professional settings, particularly across tech, commerce, and educated urban communication.</p>
    <p className="text-slate-700 mb-4">[12] Detection precision for Indonesian AI material reaches roughly an 83% true positive rate alongside an 85% true negative rate across standard benchmark test sets. Evaluating Indonesian proves trickier than examining other tongues because its relatively streamlined morphological framework leaves fewer noticeable computational fingerprints compared to heavily inflected languages. Register mismatch detection (identifying formal bahasa baku used in relaxed settings) yields an 88%+ accuracy level as our leading indicator. Evaluating bahasa gaul authenticity hits 84%+ for casual online material. Precision drops somewhat when inspecting formal Indonesian academic and corporate prose where human output and AI output share nearly identical stylistic traits.</p>
    <p className="text-slate-700 mb-4">[13] Our API offers smooth integration into Indonesian publishing, pedagogical, and enterprise processing pipelines. Text in Indonesian is processed through UTF-8 encoding, correctly managing the standard Latin characters found in the language. Configurable parameters covering stylistic context, geographic dialect influence, and content category enable granular system tuning. Outputted JSON reports provide overall likelihood scores, confidence intervals, register consistency metrics, affix frequency audits, bahasa gaul authenticity metrics for informal copy, alongside additional localized Indonesian linguistic assessments. The batch processing feature effortlessly supports large-scale Indonesian content screening.</p>
  </div>
</section>
);

export const indonesianAiDetectorContent: ToolContent = {
  writeUp: <WriteUp />,
  faqs: [
    {
      category: 'general',
      question: '[14] What is the primary AI detection signal for Indonesian text?',
      answer: '[15] The foremost indicator of Indonesian machine-authored copy is an obvious formal-informal register mismatch. Bahasa Indonesia maintains a broad divergence between standard formal bahasa baku (the standard for scholarly research, state documentation, news outlets) and casual everyday Indonesian (prevalent in routine discussions, social networks, casual digital exchanges). Machine-generated Indonesian invariably selects formal bahasa baku irrespective of setting — producing rigid, stiff copy across casual channels where real people naturally rely on truncated expressions, local dialect loans, English loanwords, and familiar bahasa gaul slang. Register appropriateness analysis — evaluating if a passage&#39;s degree of formality fits its intended audience — attains 88%+ accuracy as the top Indonesian AI detection marker.',
    },
    {
      category: 'detection',
      question: '[16] What is bahasa gaul and why does its absence signal AI generation?',
      answer: '[17] Known as bahasa gaul, this casual Indonesian vernacular dominates daily interpersonal conversations, social channels, and informal online dialogues. The style relies on familiar personal pronouns (such as gue/gw for I, and lu/lo for you), conversational negative terms (nggak/ngga replacing standard tidak/bukan), current urban slang, inventive word shortenings, phonetic adaptations, alongside an organic fusion of standard Indonesian, provincial vocabulary, and English terms typical of genuine Indonesian internet interactions. Machine-written informal Indonesian frequently inserts stiff formal substitutions for everyday terms — using "saya" rather than "gue," or "tidak" instead of "nggak" — resulting in tone-deaf phrasing. Evaluating bahasa gaul authenticity delivers an 84%+ detection accuracy rate across casual digital Indonesian media.',
    },
    {
      category: 'detection',
      question: '[18] How does Indonesian affix morphology contribute to AI detection?',
      answer: '[19] The intricate affix framework of Indonesian — spanning prefixes (me-, ber-, di-, ke-, ter-, pe-), suffixes (-kan, -i, -an), and circumfixes — demands context-driven precision that automated systems regularly confuse. Automated Indonesian occasionally applies the wrong prefix relative to verb transitivity, overuses passive di- constructions where active me- phrasing would feel natural, or applies affixes with far less variety than genuine human prose demonstrates. Evaluating affix usage naturalness uncovers whether grammatical selections stem from true linguistic mastery or reflect predictable machine default preferences. This metric proves most potent across formal Indonesian contexts where affix structures are widespread and any departures from genuine cadence stand out prominently.',
    },
    {
      category: 'regional',
      question: '[20] Does the detector handle regional language influences on Indonesian writing?',
      answer: '[21] Yes, regional language substrate analysis detects major local dialect markers embedded in human-authored Indonesian copy. Native speakers hailing from diverse islands naturally inject distinctive dialect features — including Javanese elements throughout Central Java Indonesian, Sundanese within West Java, or Minang across West Sumatra — evident in diction, vernacular phrasing, and rhetorical rhythm. Computer-generated Indonesian lacks these organic geographic markers, yielding flat phrasing stripped of local personality. Whenever a passage is attributed to a specific province, missing expected regional influences serves as an indicator of automated writing. This geographic screening remains available, though with lower overall confidence than generic Indonesian analysis due to dialect complexity and sparse localized sample datasets.',
    },
    {
      category: 'academic',
      question: '[22] Can Indonesian universities and schools use the detector for academic integrity?',
      answer: '[23] Yes, academic calibration incorporates classic Indonesian higher education formats (skripsi, tesis, disertasi) along with their specific structural mandates outlined in DIKTI guidelines. Distinct institutional formatting criteria that diverge from baseline DIKTI rules often cause AI generators to default to generic academic layouts rather than adhering to campus-specific rules — creating a clear identification marker. Secondary education assignments (SMA essays) feature dedicated adjustments mirroring standard Bahasa Indonesia high school curricula. The batch mechanism processes extensive student submission volumes. Clear analytical summaries assist educators during grading. Academic bodies throughout Indonesia should construct unambiguous generative tool rules aligned with national DIKTI AI governance guidance prior to deploying detection within institutional integrity programs.',
    },
    {
      category: 'professional',
      question: '[24] Is the detector useful for Indonesian digital media and journalism?',
      answer: '[25] Yes, major Indonesian news companies — such as Detik, Kompas, Tribun, and peer publications — gain substantial value from screening incoming articles for synthetic material. Domestic news formats rely on distinct stylistic rules that machine tools can only roughly simulate. Within digital marketing sectors, regional marketplace platforms (Tokopedia, Shopee, Bukalapak), and creator ecosystems, automated detection validates internal content integrity standards. Synthetic Indonesian product listings, social promotional copy, and influencer updates regularly misapply formal bahasa baku in settings demanding casual, persuasive copy — a flaw readily caught via register evaluation. The platform API integrates cleanly with editorial workflows for automated review prior to publication.',
    },
    {
      category: 'accuracy',
      question: 'What is the accuracy level for spotting AI-written Indonesian text?',
      answer: 'The system reaches roughly an 83% true positive rate and an 85% true negative rate on test benchmarks. Indonesian analysis is harder than in morphologically complex tongues because simpler structures offer fewer AI markers. Register mismatch detection (formal bahasa baku used in casual settings) hits 88%+ accuracy as the main indicator. Bahasa gaul authenticity checking hits 84%+ for casual online spaces. Accuracy drops slightly in formal Indonesian academic and professional prose where human and AI styles overlap the most. Every result includes confidence intervals. Benchmarks refresh every quarter.',
    },
    {
      category: 'technical',
      question: 'How does the tool process Indonesian-English code-switching?',
      answer: 'Indonesian-English code-switching is frequent among educated urban speakers in Indonesia, especially within tech, commerce, and social networks. English borrowed words and terms blended into Indonesian are natural traits rather than AI clues — the tool views them as normal modern Indonesian. The system evaluates whether code-switching habits match real Indonesian mixing norms instead of awkward blending. True Indonesian code-switching follows style and register rules; AI sometimes switches languages at weird frequencies for the context. The proportion and flow of Indonesian-English blending aid in checking register authenticity.',
    },
    {
      category: 'privacy',
      question: 'How do you secure submitted Indonesian text?',
      answer: 'All uploaded text travels through secure encrypted paths without long-term storage. User sessions remain separated and data is wiped post-analysis. No text goes toward model training without direct permission. For Indonesian enterprise users, data handling complies with Indonesia\'s Personal Data Protection Law (UU PDP, active since 2024) standards for personal data management. Corporate setups accommodate Indonesian data residency rules, ensuring all data processing stays inside Indonesia per UU PDP mandates. Indonesian-language privacy guides exist for corporate compliance files.',
    },
    {
      category: 'general',
      question: 'How long does Indonesian text need to be for dependable analysis?',
      answer: 'Dependable Indonesian detection needs around 150-200 words. Indonesian uses the Latin alphabet and relatively short words (root words are normally 2-4 syllables), meaning word counts align closely with English. Style analysis works best with several paragraphs to check overall consistency. Bahasa gaul authenticity reviews for casual text require enough informal slang examples. For official evaluations, texts over 400 words give the strongest outcomes. Very brief Indonesian pieces (below 100 words) get tagged with clear low-confidence warnings. When text is limited, checking the entire document rather than single snippets boosts reliability.',
    },
    {
      category: 'detection',
      question: 'Which formal Indonesian expressions does AI tend to overuse?',
      answer: 'AI-created formal Indonesian frequently overuses standard transition phrases: "Dalam hal ini" (in this regard), "Perlu diketahui bahwa" (it should be known that), "Berdasarkan hal tersebut" (based on the above), "Dengan demikian" (thus/therefore), "Sebagaimana telah disebutkan" (as has been mentioned), plus "Dalam konteks ini" (in this context) show up at predictable intervals in AI Indonesian. Human Indonesian authors employ these connectors more carefully, often favoring basic transitions or implied logical links in formal Indonesian. The rigid placement of formal transition words — at every paragraph edge — acts as an AI marker in Indonesian academic and professional writing.',
    },
    {
      category: 'academic',
      question: 'How does the engine process writing from Indonesian middle and high schools (SMA/SMP)?',
      answer: 'School-level calibration factors in the natural variance of Indonesian student writing skills and the specific composition rules taught under Indonesia\'s Bahasa Indonesia framework. High school students learn strict essay structures (teks argumentasi, teks eksposisi, teks narasi) featuring unique guidelines. Evaluation for school environments applies age-appropriate, curriculum-matched calibration instead of university-level standards. The tool differentiates between clumsy yet genuine student work (messy but authentic patterns) and AI-generated content (uniformly correct but poorly suited or formulaic for the register). This separation matters greatly for fair evaluation in school settings where student writing proficiency differs broadly.',
    },
    {
      category: 'detection',
      question: 'In what way does the detector process Indonesian influenced by Javanese or Sundanese?',
      answer: 'Javanese and Sundanese represent Indonesia\'s two largest regional languages, strongly shaping the Indonesian used by speakers across Java. Javanese impact shows through borrowed vocabulary, specific polite phrasing habits, and stylistic choices rooted in Javanese cultural norms (particularly concerning indirectness and refinement). Sundanese impact similarly manifests via distinct terms and rhetorical structures. The detector identifies these regional substrate effects as genuine markers of Indonesian authorship. Artificial intelligence generated Indonesian lacks these regional elements, yielding a "generic Indonesian" devoid of the local flavor that authentic regional Indonesian writers naturally include. Regional substrate analysis remains accessible though carries reduced confidence compared to standard Indonesian recognition.',
    },
    {
      category: 'usage',
      question: 'Does the Indonesian AI Detector provide value for Indonesian e-commerce websites?',
      answer: 'Indeed, Indonesian e-commerce represents a major detection use case. Indonesia hosts one of the planet\'s liveliest e-commerce sectors, featuring platforms like Tokopedia, Shopee, and Bukalapak that demand authentic seller messages and product details. AI-created Indonesian product descriptions, user reviews, and vendor communications frequently employ overly rigid bahasa baku in situations requiring compelling informal-register Indonesian for e-commerce. Detection assists marketplaces in spotting machine-generated text that might not reflect real human seller activity, backing platform trustworthiness and consumer protection goals. A batch processing API supports high-volume e-commerce content filtering.',
    },
    {
      category: 'general',
      question: 'How does the Indonesian AI Detector compare against general multilingual detectors?',
      answer: 'General multilingual detectors perform poorly on Indonesian for two primary reasons. First, the relatively basic morphology of Indonesian means English-derived artificial intelligence signals fail to transfer effectively — formal Indonesian writing lacks the structural complexity that English-centered models rely upon as indicators. Second, the most dependable Indonesian AI indicators (formal-informal register mismatches, inauthentic bahasa gaul, and missing regional substrates) demand Indonesian-focused calibration. Generic tools flagging Indonesian using complexity markers borrowed from English trigger both false positives (genuine complex formal Indonesian) and false negatives (AI Indonesian avoiding complexity markers while still failing register authenticity). Indonesian-focused detection delivers vastly superior precision.',
    },
    {
      category: 'technical',
      question: 'Does the Indonesian AI Detector provide API access?',
      answer: 'Yes, the API allows integration within Indonesian editorial, educational, and corporate workflows. Endpoints accept Indonesian Latin-script UTF-8 text alongside optional settings covering register context, regional variety influence, and content format. JSON outputs supply probability metrics, confidence intervals, register suitability evaluations, affix utilization analysis, bahasa gaul authenticity checks, and Indonesian-specific feature reports. Batch endpoints accommodate high-volume processing. Indonesian-language API documentation is provided. The API connects with Indonesian LMS systems (Moodle, Sistem Informasi Akademik) utilized throughout Indonesian universities, alongside major Indonesian CMS solutions for media and e-commerce integration.',
    },
    {
      category: 'detection',
      question: 'Can the detector differentiate machine-generated Indonesian from Indonesian penned by non-native speakers?',
      answer: 'Non-native Indonesian authors display patterns from their mother tongues that differ significantly from artificial intelligence generation markers. English speakers crafting Indonesian exhibit English-transfer traits; Javanese or Sundanese speakers writing Indonesian display regional language substrate influences; Dutch heritage speakers demonstrate older Dutch-influenced Indonesian structures. The detector separates these non-native patterns from AI creation via multi-signal evaluation. Non-native Indonesian presents transfer mistakes and substrate impacts alongside authentic human content indicators; AI Indonesian demonstrates consistent register formality irrespective of context, fixed affix application routines, and a complete absence of regional substrate effects. Lower-confidence tagging applies to beginner Indonesian learner text.',
    },
    {
      category: 'accuracy',
      question: 'In what manner does the Indonesian AI Detector maintain up-to-date performance?',
      answer: 'The detection system receives quarterly updates against current AI outputs, featuring adjustments for Indonesian-specific AI capabilities originating from global platforms and domestic technology firms building AI in Bahasa Indonesia. Each update benchmarks against the newest models\' Indonesian outputs, detects fresh generation patterns, and recalibrates detection thresholds. Register analysis models receive updates whenever AI solutions demonstrate enhanced informal Indonesian generation. Bahasa gaul terminology and convention calibration adapts to capture the rapidly changing informal Indonesian digital language environment. Human baseline calibration updates to reflect shifting Indonesian digital writing standards. Benchmark performance outcomes appear in both Indonesian and English following every update cycle.',
    },
    {
      category: 'usage',
      question: 'How ought Indonesian teachers interpret detection outcomes?',
      answer: 'Detection outcomes offer probabilistic evidence demanding educator discretion. High-confidence scores (85%+) paired with narrow confidence intervals point to strong AI indicators worth examining. Moderate scores (60-85%) merit inspection rather than immediate action. Scores beneath 60% should never provoke action absent supplementary proof. Indonesian instructors need to factor in the student\'s regional language background (potentially yielding authentic Indonesian featuring non-standard attributes), their formal education level, and whether the writing assignment demanded formal or informal Indonesian. Every consequential academic decision must incorporate human evaluation of specific flagged segments and consideration of extra evidence beyond mere detection scores, aligning with Indonesian higher education due process expectations.',
    },
  ],
};



